/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaControle;
import Controle.CategoriaControle;
import Controle.ClienteControle;
import Controle.ConsoleControle;
import Controle.DevolucaoControle;
import Controle.JogoControle;
import Controle.JogoLocacaoControle;
import Controle.LocacaoControle;
import Controle.LucroControle;
import Controle.VendedorControle;
import Modelo.CaixaBEAN;
import Modelo.ClienteBEAN;
import Modelo.DevolucaoBEAN;
import Modelo.JogoBEAN;
import Modelo.JogoLocacaoBEAN;
import Modelo.JogoLocacaoPK;
import Modelo.LocacaoBEAN;
import Modelo.VendedorBEAN;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alef
 */
public class FRMAluguelNovo extends javax.swing.JFrame {

    private final String numeros = "0123456789";
    private DefaultTableModel modelJogo;
    private DefaultTableModel modelCarro;
    private DefaultTableModel modelDev;
    private JogoControle contJog = new JogoControle();
    private ClienteControle contCli = new ClienteControle();
    private ConsoleControle cControle = new ConsoleControle();
    private CategoriaControle catControle = new CategoriaControle();
    private VendedorControle cVend = new VendedorControle();
    private CaixaControle cCaixa = new CaixaControle();
    private LucroControle cLucro = new LucroControle();
    private LocacaoControle contLoc = new LocacaoControle();
    private DevolucaoControle contDev = new DevolucaoControle();
    private JogoLocacaoControle cJl = new JogoLocacaoControle();
    private ArrayList<JogoBEAN> insertJogo = new ArrayList<JogoBEAN>();

    /**
     * Creates new form FRMAluguelNovo
     */
    public FRMAluguelNovo() {
        initComponents();
        this.setLocationRelativeTo(null);
        try {
            lbVendedorCod.setText(String.valueOf(FRMLogin.user.getVendedorCodigo()));
        } catch (Exception e) {
            lbVendedorCod.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpGuia = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfDataAluguel = new javax.swing.JFormattedTextField();
        lbVendedorCod = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfPrecoUnit = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJogo = new javax.swing.JTable();
        tfChaveJogo = new javax.swing.JTextField();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableCarrinho = new javax.swing.JTable();
        jPanel4 = new javax.swing.JPanel();
        jButton12 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jpCompra = new javax.swing.JPanel();
        lbPrecoTT = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        tfPrecoPago = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfTroco = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tfDataDevolução = new javax.swing.JFormattedTextField();
        lbCliNome = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpCompra1 = new javax.swing.JPanel();
        lbValorDev = new javax.swing.JLabel();
        lbCliNome2 = new javax.swing.JLabel();
        tfCliente2 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfMulta = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfDataDevoluçãoReal = new javax.swing.JFormattedTextField();
        tfTotalDev = new javax.swing.JLabel();
        tfCodLoc = new javax.swing.JTextField();
        lbDataDev = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tableJogoDev = new javax.swing.JTable();
        jPanel11 = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados da Locação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Data: ");

        try{
            javax.swing.text.MaskFormatter faixa= new javax.swing.text.MaskFormatter("##/##/####");
            tfDataAluguel = new javax.swing.JFormattedTextField(faixa);
        }
        catch (Exception e){
        }

        lbVendedorCod.setText("...");
        lbVendedorCod.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("Preço unitário:");

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendedorCod, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addComponent(tfDataAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel22)
                        .addComponent(tfDataAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(tfPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10))
                    .addComponent(lbVendedorCod))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tableJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJogoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableJogo);

        tfChaveJogo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfChaveJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChaveJogoActionPerformed(evt);
            }
        });
        tfChaveJogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChaveJogoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfChaveJogoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfChaveJogoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfChaveJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfChaveJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton9.setText("Adicionar Jogo");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton10.setText("Remover Jogo");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho de Aluguel", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Quantidade", "Total"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tableCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarrinhoMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tableCarrinho);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jButton12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton12.setText("Fechamento");
        jButton12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGap(44, 44, 44)
                        .addComponent(jButton9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton10)
                        .addGap(43, 43, 43)))
                .addContainerGap())
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGap(134, 134, 134)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpGuia.addTab("Aluguel", jPanel12);

        jpCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Locação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lbPrecoTT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbPrecoTT.setText("0");
        lbPrecoTT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Preço Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Preço Pago:");

        tfPrecoPago.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoPagoActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Troco:");

        tfCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfClienteKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("Data-Devolução:");

        try{
            javax.swing.text.MaskFormatter faixa= new javax.swing.text.MaskFormatter("##/##/####");
            tfDataDevolução = new javax.swing.JFormattedTextField(faixa);
        }
        catch (Exception e){
        }

        lbCliNome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        javax.swing.GroupLayout jpCompraLayout = new javax.swing.GroupLayout(jpCompra);
        jpCompra.setLayout(jpCompraLayout);
        jpCompraLayout.setHorizontalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addGroup(jpCompraLayout.createSequentialGroup()
                                .addGap(114, 114, 114)
                                .addComponent(tfDataDevolução, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lbPrecoTT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfPrecoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCliNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jpCompraLayout.setVerticalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCliente)
                    .addComponent(lbCliNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(15, 15, 15)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfDataDevolução, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(tfPrecoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel3))
                    .addComponent(lbPrecoTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Gravar Locação");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton2.setText("Localizar Devolução");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2)
                .addGap(363, 363, 363))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addComponent(jpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 306, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 173, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        tpGuia.addTab("Fechamento", jPanel3);

        jpCompra1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Devolução", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lbValorDev.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Valor Devolução", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lbCliNome2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tfCliente2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfCliente2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCliente2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCliente2KeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Multa:");

        tfMulta.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfMultaKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfMultaKeyTyped(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Data Devolução real:");

        try{
            javax.swing.text.MaskFormatter faixa= new javax.swing.text.MaskFormatter("##/##/####");
            tfDataDevoluçãoReal = new javax.swing.JFormattedTextField(faixa);
        }
        catch (Exception e){
        }

        tfTotalDev.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Total a Pagar", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tfCodLoc.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código Locação", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfCodLoc.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfCodLocKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCodLocKeyTyped(evt);
            }
        });

        lbDataDev.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Data Devolução esperada", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tableJogoDev.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableJogoDev.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJogoDevMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tableJogoDev);

        javax.swing.GroupLayout jpCompra1Layout = new javax.swing.GroupLayout(jpCompra1);
        jpCompra1.setLayout(jpCompra1Layout);
        jpCompra1Layout.setHorizontalGroup(
            jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompra1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompra1Layout.createSequentialGroup()
                        .addComponent(tfCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                        .addComponent(lbCliNome2, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24))
                    .addGroup(jpCompra1Layout.createSequentialGroup()
                        .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbValorDev, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jpCompra1Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCompra1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfDataDevoluçãoReal, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCompra1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(tfTotalDev, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(jpCompra1Layout.createSequentialGroup()
                        .addComponent(tfCodLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbDataDev, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCompra1Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                        .addGap(21, 21, 21))))
        );
        jpCompra1Layout.setVerticalGroup(
            jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompra1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lbCliNome2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfCliente2))
                .addGap(18, 18, 18)
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(tfCodLoc)
                    .addComponent(lbDataDev, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbValorDev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel8)
                        .addComponent(tfDataDevoluçãoReal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(tfTotalDev, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 74, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jButton3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton3.setText("Gravar Devolução");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(119, 119, 119)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        tpGuia.addTab("Devolução", jPanel1);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel2.setText("Realizar Aluguel e Devolução");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tpGuia, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2)
                .addGap(75, 75, 75))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tpGuia))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void povoaTabelaJogo(int c) {
        modelJogo = criaTabelaJogo();
        modelJogo.addColumn("Jogo");
        modelJogo.addColumn("Quantidade");
        for (JogoBEAN j : contJog.listarALL()) {
            if ((j.getJoCodigo() == c) && (j.getJoTipo().equals("Aluguel"))) {
                modelJogo.addRow(new Object[]{j.getJoNome(), j.getJoQtd()});
            }
        }
        tableJogo.setModel(modelJogo);
    }

    private DefaultTableModel criaTabelaJogo() {
        DefaultTableModel cTable = new DefaultTableModel() {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class};
            boolean[] canEdit = new boolean[]{
                false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;
        };
    return cTable;
    }

    private void preencheTabelaCarro() {
        modelCarro = criaTabelaCarro();
        modelCarro.addColumn("Jogo");
        modelCarro.addColumn("Quantidade");
        modelCarro.addColumn("Total");
        for (JogoBEAN j : insertJogo) {
            modelCarro.addRow(new Object[]{j.getJoNome(), j.getJoQtd(), (j.getJoPrecoPadrao())});
        }
        tableCarrinho.setModel(modelCarro);
    }

    private DefaultTableModel criaTabelaCarro() {
        DefaultTableModel cTable = new DefaultTableModel() {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class, java.lang.Float.class};
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;
        };
    return cTable;
    }

    private void povoaTabelaDev(int c) {
        modelDev = criaTabelaJogo();
        modelDev.addColumn("Jogo");
        modelDev.addColumn("Quantidade");

        for (JogoLocacaoBEAN jl : cJl.listarALL()) {
            if (jl.getChaveComposta().getLocacao().getLocCodigo() == c) {
                for (JogoBEAN j : contJog.listarALL()) {
                    if (j.getJoCodigo() == jl.getChaveComposta().getJogo().getJoCodigo()) {
                        modelDev.addRow(new Object[]{j.getJoNome(), jl.getJlQtd()});
                    }
                }

            }
        }

        tableJogoDev.setModel(modelDev);
    }

    private void tableJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableJogoMouseClicked

    private void tfChaveJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChaveJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChaveJogoActionPerformed

    private void tfChaveJogoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogoKeyPressed

    }//GEN-LAST:event_tfChaveJogoKeyPressed

    private void tfChaveJogoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogoKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfChaveJogoKeyTyped

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (tfPrecoUnit.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Preencha o preço unitário");
        } else {
            float preco = Float.parseFloat(tfPrecoUnit.getText());        
                JogoBEAN j = contJog.localizarCodigo(Integer.parseInt(tfChaveJogo.getText()));
                int qtd = Integer.parseInt(JOptionPane.showInputDialog("Digite a Quantidade de jogos"));
                if ((qtd <= j.getJoQtd()) && (qtd > 0)) {
                    JogoBEAN wtf = new JogoBEAN();
                    wtf.setJoCodigo(j.getJoCodigo());
                    wtf.setJoNome(j.getJoNome());
                    wtf.setJoQtd(qtd);
                    wtf.setJoPrecoPadrao(preco * qtd);
                    insertJogo.add(wtf);
                    j.setJoQtd(j.getJoQtd() - qtd);
                    contJog.editar(j);
                    preencheTabelaCarro();
                    try {
                        povoaTabelaJogo(Integer.parseInt(tfChaveJogo.getText()));
                    } catch (Exception e) {
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Quantidade inválida");
                }        
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
        if (tableCarrinho.getSelectedRow() != -1) {
            int i = tableCarrinho.getSelectedRow();

            JogoBEAN a = insertJogo.get(i);
            JogoBEAN j = contJog.localizarCodigo(a.getJoCodigo());
            j.setJoQtd(j.getJoQtd() + a.getJoQtd());
            contJog.editar(j);

            insertJogo.remove(i);
            preencheTabelaCarro();

            try {
                povoaTabelaJogo(Integer.parseInt(tfChaveJogo.getText()));
            } catch (Exception e) {

            }

        } else {
            JOptionPane.showMessageDialog(null, "Selecione o jogo");
        }
    }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton12ActionPerformed
        if (tfPrecoUnit.getText().equals("") || tfDataAluguel.getText().equals("")
                || tableCarrinho.getRowCount() == 0) {
            JOptionPane.showMessageDialog(null, "Erro! Preencha todos os dados");
        } else {
            int qtd = 0;
            for (JogoBEAN j : insertJogo) {
                qtd += j.getJoQtd();
            }
            float preco = Float.parseFloat(tfPrecoUnit.getText()) * qtd;
            lbPrecoTT.setText(String.valueOf(preco));
            tpGuia.setSelectedIndex(1);
        }
    }//GEN-LAST:event_jButton12ActionPerformed

    private void tableCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarrinhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCarrinhoMouseClicked

    private boolean verificaCampos() {
        if (tableCarrinho.getRowCount() == 0 || lbVendedorCod.getText().equals("...")
                || tfPrecoUnit.getText().equals("...") || tfDataAluguel.getText().equals("")
                || tfDataDevolução.getText().equals("") || tfPrecoPago.getText().equals("")
                || tfTroco.getText().equals("") || lbPrecoTT.getText().equals("...")
                || lbCliNome.getText().equals("Cliente não encontrado") || tfCliente.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    private void cadastroLoc() {
        LocacaoBEAN l = new LocacaoBEAN();

        try {
            String dataString = tfDataAluguel.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
            l.setLocDataAluguel(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        l.setLocPreçoTotal(Float.parseFloat(lbPrecoTT.getText()));
        float entrada = Float.parseFloat(tfPrecoPago.getText()) - Float.parseFloat(tfTroco.getText());
        l.setLocEntrada(entrada);

        try {
            String dataString = tfDataDevolução.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
            l.setLocDataDevolucao(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        l.setLocStatus("Pendente");
        l.setLocPrecoUnit(Float.parseFloat(tfPrecoUnit.getText()));

        try {
            VendedorBEAN vend = cVend.localizar(Integer.valueOf(lbVendedorCod.getText()));
            l.setVendedor(vend);
        } catch (Exception e) {
            VendedorBEAN vend = cVend.localizar(0);
            l.setVendedor(vend);
        }

        try {
            ClienteBEAN c = contCli.localizarCodigo(Integer.valueOf(tfCliente.getText()));
            l.setCliente(c);
        } catch (Exception e) {
            ClienteBEAN c = contCli.localizarCodigo(0);
            l.setCliente(c);
        }

        contLoc.cadastrar(l);

        for (JogoBEAN j : insertJogo) {
            JogoLocacaoPK jlPK = new JogoLocacaoPK();
            jlPK.setJogo(j);
            jlPK.setLocacao(l);
            JogoLocacaoBEAN a = new JogoLocacaoBEAN();
            a.setChaveComposta(jlPK);
            a.setJlQtd(j.getJoQtd());
            cJl.cadastrar(a);
        }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (verificaCampos()) {
            try {
                cadastroLoc();
                limpaCampos();
                //insertJogo.clear();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Locação Cadastrada com sucesso.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro!Preencha todos os campos.");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void limpaCampos() {
        tfChaveJogo.setText("");
        tfCodLoc.setText("");
        tfCliente.setText("");
        tfCliente2.setText("");
        lbCliNome.setText("");
        lbCliNome2.setText("");
        tfCodLoc.setText("");
        tfDataAluguel.setText("");
        tfDataDevolução.setText("");
        tfDataDevoluçãoReal.setText("");
        tfMulta.setText("");
        tfTotalDev.setText("");
        lbDataDev.setText("");
        lbPrecoTT.setText("");
        lbValorDev.setText("");
        lbVendedorCod.setText("");
    }

    private boolean verificaDev() {
        if (tfCliente2.getText().equals("")
                || lbCliNome2.getText().equals("Cliente não encontrado")
                || tfCodLoc.getText().equals("")
                || lbCliNome.getText().equals("Essa Locação já foi Devolvida")
                || lbCliNome.getText().equals("Locação não encontrada")
                || tfDataDevoluçãoReal.getText().equals("")
                || tfMulta.getText().equals("")
                || tfTotalDev.getText().equals("")) {
            return false;
        } else {
            return true;
        }

    }

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (verificaDev()) {
            CaixaBEAN caixa = cCaixa.localizar(1);
            LocacaoBEAN l = contLoc.localizarLoc(Integer.parseInt(tfCodLoc.getText()));
            DevolucaoBEAN dev = new DevolucaoBEAN();
            dev.setCaixa(caixa);
            dev.setLocacao(l);

            try {
                String dataString = tfDataDevoluçãoReal.getText();
                DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
                dev.setDevData(data);
            } catch (ParseException e) {
                e.printStackTrace();
            }

            dev.setDevMulta(Float.parseFloat(tfMulta.getText()));
            dev.setDevValor(Float.parseFloat(tfTotalDev.getText()));
            contDev.cadastrar(dev);

            caixa.setCaixaDinheiro(caixa.getCaixaDinheiro() + dev.getDevValor());
            cCaixa.editar(caixa);

            for (JogoLocacaoBEAN jl : cJl.listarALL()) {
                if (jl.getChaveComposta().getLocacao().getLocCodigo() == l.getLocCodigo()) {
                    JogoBEAN j = contJog.localizarCodigo(jl.getChaveComposta().getJogo().getJoCodigo());
                    j.setJoQtd(j.getJoQtd() + jl.getJlQtd());
                    contJog.editar(j);
                }
            }

            l.setLocStatus("Paga");
            contLoc.editar(l);
            JOptionPane.showMessageDialog(null, "Devolução feita com sucesso");
            limpaCampos();
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos");
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tfChaveJogoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogoKeyReleased
        int c;
        if (tfChaveJogo.getText().equals("")) {
            c = 0;
        } else {
            c = Integer.parseInt(tfChaveJogo.getText());
        }
        povoaTabelaJogo(c);
    }//GEN-LAST:event_tfChaveJogoKeyReleased

    private void tfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyReleased
        try {
            ClienteBEAN c = contCli.localizarCodigo(Integer.parseInt(tfCliente.getText()));
            lbCliNome.setText(c.getCliNome());
        } catch (Exception e) {
            lbCliNome.setText("Cliente não encontrado");
        }
    }//GEN-LAST:event_tfClienteKeyReleased

    private void tfPrecoPagoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoPagoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoPagoActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        tpGuia.setSelectedIndex(2);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tfCliente2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCliente2KeyReleased
        try {
            ClienteBEAN a = contCli.localizarCodigo(Integer.parseInt(tfCliente2.getText()));
            lbCliNome2.setText(a.getCliNome());
            int count = 0;
            int loc = 0;
            for (LocacaoBEAN l : contLoc.listarALL()) {
                if (l.getCliente().getCliCodigo() == a.getCliCodigo()) {
                    if (l.getLocStatus().equals("Pendente")) {
                        count++;
                        loc = l.getLocCodigo();
                    }
                }
            }
            if (count == 1) {
                LocacaoBEAN c = contLoc.localizarLoc(loc);
                tfCodLoc.setText(String.valueOf(c.getLocCodigo()));
                buscarLoc(c);
            } else {
                lbDataDev.setText("");
                lbValorDev.setText("");
                povoaTabelaDev(0);
            }
        } catch (Exception e) {
            lbCliNome2.setText("Cliente não encontrado");
            lbDataDev.setText("");
            lbValorDev.setText("");
            povoaTabelaDev(0);
        }
    }//GEN-LAST:event_tfCliente2KeyReleased

    private void tfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfClienteKeyTyped

    private void tfCliente2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCliente2KeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfCliente2KeyTyped

    private void tfCodLocKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodLocKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfCodLocKeyTyped
    private void buscarLoc(LocacaoBEAN c) {
        if (c.getLocStatus().equals("Pendente")) {
            lbDataDev.setText(String.valueOf(c.getLocDataDevolucao()));
            float valor = c.getLocPreçoTotal() - c.getLocEntrada();
            lbValorDev.setText(String.valueOf(valor));
            povoaTabelaDev(c.getLocCodigo());
        } else {
            lbDataDev.setText("");
            lbValorDev.setText("");
            povoaTabelaDev(0);
        }
    }
    private void tfCodLocKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCodLocKeyReleased
        try {
            LocacaoBEAN c = contLoc.localizarLoc(Integer.parseInt(tfCodLoc.getText()));
            buscarLoc(c);
        } catch (Exception e) {
            lbDataDev.setText("");
            lbValorDev.setText("");
            povoaTabelaDev(0);
        }
    }//GEN-LAST:event_tfCodLocKeyReleased
    private boolean verificarValor() {
        if (lbValorDev.getText().equals("") || tfMulta.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }
    private void tableJogoDevMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJogoDevMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableJogoDevMouseClicked

    private void tfMultaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMultaKeyReleased
        float valorReal = 0;
        try {
            valorReal = Float.parseFloat(lbValorDev.getText()) + Float.parseFloat(tfMulta.getText());
            tfTotalDev.setText(String.valueOf(valorReal));
        } catch (Exception e) {
            valorReal = Float.parseFloat(lbValorDev.getText());
            tfTotalDev.setText(String.valueOf(valorReal));
        }
    }//GEN-LAST:event_tfMultaKeyReleased

    private void tfMultaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfMultaKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfMultaKeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMAluguelNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMAluguelNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMAluguelNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMAluguelNovo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMAluguelNovo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton12;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JPanel jpCompra;
    private javax.swing.JPanel jpCompra1;
    private javax.swing.JLabel lbCliNome;
    private javax.swing.JLabel lbCliNome2;
    private javax.swing.JLabel lbDataDev;
    private javax.swing.JLabel lbPrecoTT;
    private javax.swing.JLabel lbValorDev;
    private javax.swing.JLabel lbVendedorCod;
    private javax.swing.JTable tableCarrinho;
    private javax.swing.JTable tableJogo;
    private javax.swing.JTable tableJogoDev;
    private javax.swing.JTextField tfChaveJogo;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JTextField tfCliente2;
    private javax.swing.JTextField tfCodLoc;
    private javax.swing.JFormattedTextField tfDataAluguel;
    private javax.swing.JFormattedTextField tfDataDevolução;
    private javax.swing.JFormattedTextField tfDataDevoluçãoReal;
    private javax.swing.JTextField tfMulta;
    private javax.swing.JTextField tfPrecoPago;
    private javax.swing.JTextField tfPrecoUnit;
    private javax.swing.JLabel tfTotalDev;
    private javax.swing.JTextField tfTroco;
    private javax.swing.JTabbedPane tpGuia;
    // End of variables declaration//GEN-END:variables
}
