/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaControle;
import Controle.EmpregoControle;
import Controle.FuncionarioControle;
import Controle.VendedorControle;
import Modelo.CaixaBEAN;
import Modelo.EmpregoBEAN;
import Modelo.EnderecoBEAN;
import Modelo.FuncionarioBEAN;
import Modelo.VendedorBEAN;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author LUCASP
 */
public class FRMCadastroFun extends javax.swing.JFrame {

    private ArrayList<FuncionarioBEAN> userD;
    private DefaultTableModel tbUsers;
    private FuncionarioControle ct = new FuncionarioControle();
    private VendedorControle vc = new VendedorControle();
    private EmpregoControle ec = new EmpregoControle();
    private CaixaControle cCaixa = new CaixaControle();
    private ArrayList<VendedorBEAN> al = vc.listarALL();

    /**
     * Creates new form FRMAdm
     */
    public FRMCadastroFun() {
        initComponents();
        this.preencheTabela();
        for (EmpregoBEAN e : ec.listarALL()) {
            cbEmprego.addItem(e);
        }
        tfNomeUser.setEnabled(false);
        tfSenhaUser.setEnabled(false);
        setResizable(false);
    }

    private void preencheTabela() {
        tbUsers = this.criaTabela();
        tbUsers.addColumn("Código");
        tbUsers.addColumn("Nome");
        tbUsers.addColumn("CPF");
        tbUsers.addColumn("Idade");
        tbUsers.addColumn("telefone");
        tbUsers.addColumn("Email");
        tbUsers.addColumn("nisPis");
        tbUsers.addColumn("Emprego");
        tbUsers.addColumn("Salário");

        userD = ct.listarALL();

        if (userD.size() > 0) {
            for (FuncionarioBEAN d : userD) {
                tbUsers.addRow(new Object[]{
                    d.getFunCodigo(),
                    d.getFunNome(),
                    d.getFunCpf(),
                    d.getFunIdade(),
                    d.getFunTelefone(),
                    d.getFunEmail(),
                    d.getFunNisPis(),
                    d.getEmprego().getEmpNome(),
                    d.getFunSalario()

                });
            }
        }
        tbFuncionario.setModel(tbUsers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel20 = new javax.swing.JLabel();
        tpGuia = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        tfSalario = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tfNPIS = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        tfIdade = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        tfCpf = new javax.swing.JFormattedTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JFormattedTextField();
        cbEmprego = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfEmail = new javax.swing.JTextField();
        jLabel18 = new javax.swing.JLabel();
        tfNomeUser = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfSenhaUser = new javax.swing.JPasswordField();
        jPanel5 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        tfRua = new javax.swing.JTextField();
        tfNumero = new javax.swing.JTextField();
        tfPais = new javax.swing.JTextField();
        tfEstado = new javax.swing.JTextField();
        tfBairro = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        tfCidade = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        btNovoDado = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        btLocalizar = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        btGravar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbFuncionario = new javax.swing.JTable();
        tfChave = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        btEditar = new javax.swing.JButton();
        btClonar = new javax.swing.JButton();
        btDemitir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        setResizable(false);

        jLabel20.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel20.setText("Gerenciar Funcionário");

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados Pessoais", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tfSalario.setEnabled(false);
        tfSalario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfSalarioKeyTyped(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Salário:");

        try{
            javax.swing.text.MaskFormatter nis= new javax.swing.text.MaskFormatter("###.#####.##-#");
            tfNPIS = new javax.swing.JFormattedTextField(nis);
        }
        catch (Exception e){
        }
        tfNPIS.setEnabled(false);
        tfNPIS.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNPISKeyTyped(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel10.setText("NIS/PIS:");

        tfIdade.setEnabled(false);
        tfIdade.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfIdadeKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel7.setText("Idade:");

        tfNome.setEnabled(false);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Nome:");

        try{
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##");
            tfCpf = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){
        }
        tfCpf.setEnabled(false);
        tfCpf.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfCpfKeyTyped(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel5.setText("CPF:");

        jLabel6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel6.setText("Telefone:");

        try{
            javax.swing.text.MaskFormatter tel= new javax.swing.text.MaskFormatter("(##)# ####-####");
            tfTelefone = new javax.swing.JFormattedTextField(tel);
        }
        catch (Exception e){
        }
        tfTelefone.setEnabled(false);

        cbEmprego.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione" }));
        cbEmprego.setEnabled(false);
        cbEmprego.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cbEmpregoItemStateChanged(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel8.setText("Emprego:");

        lbCodigo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCodigo.setText("...");
        lbCodigo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel3.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel3.setText("Email:");

        tfEmail.setEnabled(false);

        jLabel18.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel18.setText("Nome de usuário:");

        tfNomeUser.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Senha:");

        tfSenhaUser.setEnabled(false);

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(8, 8, 8)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfNome))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel5)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(jLabel7)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel6)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel7Layout.createSequentialGroup()
                            .addComponent(jLabel10)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfNPIS, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(34, 34, 34)
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(tfEmail)))
                    .addGroup(jPanel7Layout.createSequentialGroup()
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(tfNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(jPanel7Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cbEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSenhaUser)
                            .addComponent(tfSalario))))
                .addGap(24, 24, 24))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(12, 12, 12)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(tfIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tfNPIS, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(tfEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(cbEmprego, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(tfNomeUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(tfSenhaUser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel12.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel12.setText("Rua :");

        jLabel13.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel13.setText("Número :");

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Bairro :");

        jLabel15.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel15.setText("Estado :");

        jLabel16.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel16.setText("País :");

        tfRua.setEnabled(false);

        tfNumero.setEnabled(false);
        tfNumero.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNumeroKeyTyped(evt);
            }
        });

        tfPais.setEnabled(false);

        tfEstado.setEnabled(false);

        tfBairro.setEnabled(false);

        jLabel17.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel17.setText("Cidade :");

        tfCidade.setEnabled(false);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel12))
                        .addGap(10, 10, 10)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfRua, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                            .addComponent(tfCidade)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfEstado)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel16))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfPais)
                            .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(tfRua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(tfNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(19, 19, 19)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel17)
                    .addComponent(tfCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPais, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(tfEstado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel16))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btNovoDado.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btNovoDado.setText("Novo Dado");
        btNovoDado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btNovoDadoActionPerformed(evt);
            }
        });

        btVoltar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });

        btLocalizar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btLocalizar.setText("Localizar");
        btLocalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLocalizarActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.setEnabled(false);
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        btGravar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btGravar.setText("Gravar");
        btGravar.setEnabled(false);
        btGravar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(btNovoDado, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btNovoDado, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGravar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btLocalizar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(169, 169, 169)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(104, 104, 104))
        );

        tpGuia.addTab("Cadastrar Funcionário", jPanel1);

        tbFuncionario.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbFuncionario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbFuncionarioMouseClicked(evt);
            }
        });
        tbFuncionario.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbFuncionarioKeyReleased(evt);
            }
        });
        jScrollPane2.setViewportView(tbFuncionario);

        tfChave.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Refinar Pesquisa", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfChave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChaveActionPerformed(evt);
            }
        });
        tfChave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChaveKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfChaveKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfChaveKeyTyped(evt);
            }
        });

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de Seleção", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btEditar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btEditar.setText("Editar");
        btEditar.setToolTipText("");
        btEditar.setEnabled(false);
        btEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditarActionPerformed(evt);
            }
        });

        btClonar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btClonar.setText("Clonar Dados");
        btClonar.setToolTipText("");
        btClonar.setEnabled(false);
        btClonar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btClonarActionPerformed(evt);
            }
        });

        btDemitir.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btDemitir.setText("Demitir");
        btDemitir.setEnabled(false);
        btDemitir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDemitirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btEditar)
                .addGap(18, 18, 18)
                .addComponent(btClonar)
                .addGap(18, 18, 18)
                .addComponent(btDemitir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btEditar)
                    .addComponent(btClonar)
                    .addComponent(btDemitir))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 298, Short.MAX_VALUE)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(264, 264, 264))
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(tfChave, javax.swing.GroupLayout.PREFERRED_SIZE, 332, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(535, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfChave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 157, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpGuia.addTab("Consultar Funcionário", jPanel3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 882, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(324, 324, 324))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel20)
                .addGap(3, 3, 3)
                .addComponent(tpGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 328, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(898, 391));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tbFuncionarioKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbFuncionarioKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_tbFuncionarioKeyReleased

    private void tbFuncionarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbFuncionarioMouseClicked
        if (tbFuncionario.getSelectedRow() != -1) {
            btEditar.setEnabled(true);
            btClonar.setEnabled(true);
            btDemitir.setEnabled(true);
        }
    }//GEN-LAST:event_tbFuncionarioMouseClicked
    private int verificaCPF() {
        int i = 0;
        for (FuncionarioBEAN c : ct.listarALL()) {
            if (c.getFunCpf().equals(tfCpf.getText())) {
                try {
                    if (c.getFunCodigo() != (Integer.valueOf(lbCodigo.getText()))) {
                        i = c.getFunCodigo();
                    }
                } catch (Exception e) {
                    i = 1;
                }

            }
        }
        return i;
    }

    private int verificapis() {
        int i = 0;
        for (FuncionarioBEAN c : ct.listarALL()) {
            if (c.getFunNisPis().equals(tfNPIS.getText())) {
                try {
                    if (c.getFunCodigo() != (Integer.valueOf(lbCodigo.getText()))) {
                        i = c.getFunCodigo();
                    }
                } catch (Exception e) {
                    i = 1;
                }
            }
        }
        return i;
    }
    private void btGravarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarActionPerformed
        if (lbCodigo.getText().equals("...")) {
            cadastrar();
        } else {
            editar();
        }
    }//GEN-LAST:event_btGravarActionPerformed

    private void tfIdadeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfIdadeKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfIdadeKeyTyped

    private void editar() {
        int c = verificaCPF();
        int e = verificapis();

        if (c == (Integer.valueOf(lbCodigo.getText()))) {
            c = 0;
        }
        if (e == (Integer.valueOf(lbCodigo.getText()))) {
            e = 0;
        }

        if (verificaCampos() == false) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else if (c == 0) {
            if (e == 0) {
                editar2();
                this.preencheTabela();
                limpaCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Pis já cadastrado no sistema. Código: " + e);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cpf  já cadastrado no sistema. Código: " + c);
        }
    }

    private void tfSalarioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfSalarioKeyTyped
        String caracteres = "0123456789.";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfSalarioKeyTyped

    private void tfNPISKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNPISKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfNPISKeyTyped

    private void tfCpfKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfCpfKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfCpfKeyTyped

    private void tfNumeroKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNumeroKeyTyped

    }//GEN-LAST:event_tfNumeroKeyTyped

    private void cbEmpregoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cbEmpregoItemStateChanged
        if (cbEmprego.getSelectedIndex() != 0) {
            EmpregoBEAN e = (EmpregoBEAN) cbEmprego.getSelectedItem();
            if (e.getEmpNome().equals("Vendedor") || (e.getEmpNome().equals("Administrador"))) {
                tfNomeUser.setEnabled(true);
                tfSenhaUser.setEnabled(true);
            } else {
                tfNomeUser.setEnabled(false);
                tfSenhaUser.setEnabled(false);
            }
        }
    }//GEN-LAST:event_cbEmpregoItemStateChanged

    private void tfChaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChaveActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChaveActionPerformed

    private void tfChaveKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveKeyPressed

    }//GEN-LAST:event_tfChaveKeyPressed

    private void tfChaveKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveKeyTyped

    }//GEN-LAST:event_tfChaveKeyTyped

    private void btEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditarActionPerformed
        limpaCampos();
        FuncionarioBEAN f = ct.localizarCodigo(Integer.parseInt(tbFuncionario.getValueAt(tbFuncionario.getSelectedRow(), 0).toString()));
        lbCodigo.setText(String.valueOf(f.getFunCodigo()));
        tfNome.setText(f.getFunNome());
        tfCpf.setText(f.getFunCpf());
        tfIdade.setText(String.valueOf(f.getFunIdade()));
        tfTelefone.setText(f.getFunTelefone());
        tfNPIS.setText(f.getFunNisPis());
        tfEmail.setText(f.getFunEmail());

        int i = 0;
        for (EmpregoBEAN emprego : ec.listarALL()) {
            i++;
            if ((f.getEmprego().getEmpCodigo() == (emprego.getEmpCodigo()))) {
                cbEmprego.setSelectedIndex(i);
            }
        }

        cbEmprego.setSelectedItem(f.getEmprego());

        tfSalario.setText(String.valueOf(f.getFunSalario()));

        for (VendedorBEAN v : vc.listarALL()) {
            if (v.getFuncionario().getFunCodigo() == f.getFunCodigo()) {
                tfNomeUser.setText(v.getVendedorNomeUsuario());
                tfSenhaUser.setText(v.getVendedorSenha());
            }
        }

        tfRua.setText(f.getEndereco().getEndRua());
        tfNumero.setText(String.valueOf(f.getEndereco().getEndNumero()));
        tfBairro.setText(f.getEndereco().getEndBairro());
        tfCidade.setText(f.getEndereco().getEndCidade());
        tfEstado.setText(f.getEndereco().getEndEstado());
        tfPais.setText(f.getEndereco().getEndPais());

        tpGuia.setSelectedIndex(0);
        habilitaCampos();
    }//GEN-LAST:event_btEditarActionPerformed

    private void btClonarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btClonarActionPerformed
        limpaCampos();
        FuncionarioBEAN f = ct.localizarCodigo(Integer.parseInt(tbFuncionario.getValueAt(tbFuncionario.getSelectedRow(), 0).toString()));
        tfNome.setText(f.getFunNome());
        tfCpf.setText(f.getFunCpf());
        tfIdade.setText(String.valueOf(f.getFunIdade()));
        tfTelefone.setText(f.getFunTelefone());
        tfNPIS.setText(f.getFunNisPis());
        tfEmail.setText(f.getFunEmail());

        int i = 0;
        for (EmpregoBEAN emprego : ec.listarALL()) {
            i++;
            if ((f.getEmprego().getEmpCodigo() == (emprego.getEmpCodigo()))) {
                cbEmprego.setSelectedIndex(i);
            }
        }

        cbEmprego.setSelectedItem(f.getEmprego());

        tfSalario.setText(String.valueOf(f.getFunSalario()));

        for (VendedorBEAN v : vc.listarALL()) {
            if (v.getFuncionario().getFunCodigo() == f.getFunCodigo()) {
                tfNomeUser.setText(v.getVendedorNomeUsuario());
                tfSenhaUser.setText(v.getVendedorSenha());
            }
        }

        tfRua.setText(f.getEndereco().getEndRua());
        tfNumero.setText(String.valueOf(f.getEndereco().getEndNumero()));
        tfBairro.setText(f.getEndereco().getEndBairro());
        tfCidade.setText(f.getEndereco().getEndCidade());
        tfEstado.setText(f.getEndereco().getEndEstado());
        tfPais.setText(f.getEndereco().getEndPais());

        tpGuia.setSelectedIndex(0);
        habilitaCampos();
    }//GEN-LAST:event_btClonarActionPerformed

    private void btDemitirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDemitirActionPerformed
        FuncionarioBEAN f = ct.localizarCodigo(Integer.parseInt(tbFuncionario.getValueAt(tbFuncionario.getSelectedRow(), 0).toString()));
        f.setFunSalario(0);
        ct.editar(f);
        preencheTabela();
    }//GEN-LAST:event_btDemitirActionPerformed

    private void btNovoDadoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btNovoDadoActionPerformed
        limpaBotoes();
        limpaCampos();
        habilitaCampos();
    }//GEN-LAST:event_btNovoDadoActionPerformed

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        FRMMenuVendedor fun = new FRMMenuVendedor();
        this.dispose();
        fun.setVisible(true);
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btLocalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLocalizarActionPerformed
        tpGuia.setSelectedIndex(1);
        preencheTabela();
    }//GEN-LAST:event_btLocalizarActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limpaBotoes();
        limpaCampos();
        desabilitaCampos();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void tfChaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveKeyReleased
        TableRowSorter sorter = null;
        DefaultTableModel model = (DefaultTableModel) tbFuncionario.getModel();
        sorter = new TableRowSorter<TableModel>(model);
        tbFuncionario.setRowSorter(sorter);
        String text = tfChave.getText();
        if (text.length() == 0) {
            sorter.setRowFilter(null);
        } else {
            sorter.setRowFilter(RowFilter.regexFilter(text));
        }
    }//GEN-LAST:event_tfChaveKeyReleased
    private void limpaBotoes() {
        btGravar.setEnabled(false);
        btCancelar.setEnabled(false);
        btEditar.setEnabled(false);
        btClonar.setEnabled(false);
        btDemitir.setEnabled(false);
    }

    private void habilitaCampos() {
        tfNome.setEnabled(true);
        tfCpf.setEnabled(true);
        tfIdade.setEnabled(true);
        tfTelefone.setEnabled(true);
        tfNPIS.setEnabled(true);
        tfEmail.setEnabled(true);
        cbEmprego.setEnabled(true);
        tfSalario.setEnabled(true);

        tfRua.setEnabled(true);
        tfCidade.setEnabled(true);
        tfEstado.setEnabled(true);
        tfNumero.setEnabled(true);
        tfBairro.setEnabled(true);
        tfPais.setEnabled(true);

        btCancelar.setEnabled(true);
        btGravar.setEnabled(true);
    }

    private void desabilitaCampos() {
        tfNome.setEnabled(false);
        tfCpf.setEnabled(false);
        tfIdade.setEnabled(false);
        tfTelefone.setEnabled(false);
        tfNPIS.setEnabled(false);
        tfEmail.setEnabled(false);
        cbEmprego.setEnabled(false);
        tfSalario.setEnabled(false);
        tfNomeUser.setEnabled(false);
        tfSenhaUser.setEnabled(false);

        tfRua.setEnabled(false);
        tfCidade.setEnabled(false);
        tfEstado.setEnabled(false);
        tfNumero.setEnabled(false);
        tfBairro.setEnabled(false);
        tfPais.setEnabled(false);

        btCancelar.setEnabled(false);
        btGravar.setEnabled(false);
    }

    private void cadastrar2() {
        FuncionarioBEAN c = new FuncionarioBEAN();
        c.setFunNome(tfNome.getText());
        c.setFunCpf(tfCpf.getText());
        c.setFunIdade(Integer.parseInt(tfIdade.getText()));
        c.setFunTelefone(tfTelefone.getText());
        c.setFunNisPis(tfNPIS.getText());
        EmpregoBEAN e = (EmpregoBEAN) cbEmprego.getSelectedItem();
        c.setEmprego(e);
        c.setFunSalario(Float.parseFloat(tfSalario.getText()));
        c.setFunEmail(tfEmail.getText());

        EnderecoBEAN end = new EnderecoBEAN();
        end.setEndRua(tfRua.getText());
        end.setEndNumero((tfNumero.getText()));
        end.setEndBairro(tfBairro.getText());
        end.setEndCidade(tfCidade.getText());
        end.setEndEstado(tfEstado.getText());
        end.setEndPais(tfPais.getText());

        c.setEndereco(end);

        CaixaBEAN ca = cCaixa.localizar(1);
        c.setCaixa(ca);

        ct.cadastrar(c);
        JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");

        cadVendedor(c, e);
    }

    private void cadastrar() {
        int c = verificaCPF();
        int e = verificapis();

        if (verificaCampos() == false) {
            JOptionPane.showMessageDialog(null, "Preencha todos os campos");
        } else if (c == 0) {
            if (e == 0) {
                cadastrar2();
                this.preencheTabela();
                limpaCampos();
            } else {
                JOptionPane.showMessageDialog(null, "Pis já cadastrado no sistema.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Cpf  já cadastrado no sistema.");
        }

    }

    private void cadVendedor(FuncionarioBEAN c, EmpregoBEAN e) {
        if (e.getEmpNome().equals("Vendedor") || e.getEmpNome().equals("Administrador")) {
            if (tfNomeUser.getText().equals("") || tfSenhaUser.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Login não cadastrado, selecione o funcionario, clique em editar e tente gravar o login novamente");
            } else {
                VendedorBEAN v = new VendedorBEAN();
                v.setFuncionario(c);
                v.setVendedorNomeUsuario(tfNomeUser.getText());
                v.setVendedorSenha(tfSenhaUser.getText());
                vc.cadastrar(v);
            }
        }
        limpaCampos();
        limpaBotoes();
    }

    private void editar2() {
        FuncionarioBEAN c = ct.localizarCodigo(Integer.parseInt(lbCodigo.getText()));
        c.setFunNome(tfNome.getText());
        c.setFunCpf(tfCpf.getText());
        c.setFunIdade(Integer.parseInt(tfIdade.getText()));
        c.setFunTelefone(tfTelefone.getText());
        c.setFunNisPis(tfNPIS.getText());
        EmpregoBEAN e = (EmpregoBEAN) cbEmprego.getSelectedItem();
        c.setEmprego(e);
        c.setFunSalario(Float.parseFloat(tfSalario.getText()));
        c.setFunEmail(tfEmail.getText());

        c.getEndereco().setEndRua(tfRua.getText());
        c.getEndereco().setEndNumero(tfNumero.getText());
        c.getEndereco().setEndBairro(tfBairro.getText());
        c.getEndereco().setEndCidade(tfCidade.getText());
        c.getEndereco().setEndEstado(tfEstado.getText());
        c.getEndereco().setEndPais(tfPais.getText());

        ct.editar(c);

        JOptionPane.showMessageDialog(null, "Funcionário Editado com sucesso");

        if (e.getEmpNome().equals("Vendedor")) {
            for (VendedorBEAN a : vc.listarALL()) {
                if (a.getFuncionario().getFunCodigo() == c.getFunCodigo()) {
                    VendedorBEAN v = vc.localizar(a.getVendedorCodigo());
                    v.setVendedorNomeUsuario(tfNomeUser.getText());
                    v.setVendedorSenha(tfSenhaUser.getText());
                    vc.editar(v);
                }
            }
        }
        limpaCampos();
        limpaBotoes();
    }

    public boolean verificaCampos() {
        if (tfNome.getText().equals("") || tfIdade.getText().equals("")
                || tfCpf.getText().equals("")
                || tfNPIS.getText().equals("") || tfTelefone.getText().equals("")
                || cbEmprego.getSelectedIndex() == 0
                || tfEmail.getText().equals("")
                || tfRua.getText().equals("")
                || tfNumero.getText().equals("")
                || tfBairro.getText().equals("")
                || tfCidade.getText().equals("")
                || tfEstado.getText().equals("")
                || tfPais.getText().equals("")) {
            return false;
        } else {
            return true;
        }
    }

    public void limpaCampos() {
        lbCodigo.setText("...");
        tfNome.setText("");
        tfCpf.setText("");
        tfIdade.setText("");
        tfTelefone.setText("");
        tfNPIS.setText("");
        cbEmprego.setSelectedIndex(0);
        tfSalario.setText("");
        tfEmail.setText("");

        tfNomeUser.setText("");
        tfSenhaUser.setText("");

        tfRua.setText("");
        tfNumero.setText("");
        tfBairro.setText("");
        tfCidade.setText("");
        tfEstado.setText("");
        tfPais.setText("");

        btEditar.setEnabled(false);

        tfNomeUser.setEnabled(false);
        tfSenhaUser.setEnabled(false);
    }

    private DefaultTableModel criaTabela() {
        //sempre que usar JTable é necessário ter um DefaulttableModel
        DefaultTableModel tbUsers = new DefaultTableModel() {
            //Define o tipo dos campos (coluna) na mesma ordem que as colunas foram criadas
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class, java.lang.String.class,
                java.lang.String.class, java.lang.String.class,};
            //define se os campos podem ser editados na propria tabela
            boolean[] canEdit = new boolean[]{
                false, false, false, false, false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;

        };
        //retorna o DefaultTableModel
    return tbUsers;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMCadastroFun.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMCadastroFun().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btClonar;
    private javax.swing.JButton btDemitir;
    private javax.swing.JButton btEditar;
    private javax.swing.JButton btGravar;
    private javax.swing.JButton btLocalizar;
    private javax.swing.JButton btNovoDado;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<Object> cbEmprego;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JTable tbFuncionario;
    private javax.swing.JTextField tfBairro;
    private javax.swing.JTextField tfChave;
    private javax.swing.JTextField tfCidade;
    private javax.swing.JFormattedTextField tfCpf;
    private javax.swing.JTextField tfEmail;
    private javax.swing.JTextField tfEstado;
    private javax.swing.JTextField tfIdade;
    private javax.swing.JFormattedTextField tfNPIS;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfNomeUser;
    private javax.swing.JTextField tfNumero;
    private javax.swing.JTextField tfPais;
    private javax.swing.JTextField tfRua;
    private javax.swing.JTextField tfSalario;
    private javax.swing.JPasswordField tfSenhaUser;
    private javax.swing.JFormattedTextField tfTelefone;
    private javax.swing.JTabbedPane tpGuia;
    // End of variables declaration//GEN-END:variables
}
