/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaControle;
import Controle.CategoriaControle;
import Controle.ConsoleControle;
import Controle.JogoControle;
import Controle.LucroControle;
import Controle.NotaDeCompraAPrazoControle;
import Controle.NotaDeCompraControle;
import Modelo.CaixaBEAN;
import Modelo.CategoriaBEAN;
import Modelo.ConsoleBEAN;
import Modelo.JogoBEAN;
import Modelo.NotaDeCompraPrazoBEAN;
import Modelo.NotaDecompraBEAN;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Alef
 */
public class FRMNotaDeCompra extends javax.swing.JFrame {

    private ConsoleControle cControle = new ConsoleControle();
    private CategoriaControle catControle = new CategoriaControle();
    private CaixaControle cCaixa = new CaixaControle();
    private ArrayList<CategoriaBEAN> catDados;
    private ArrayList<ConsoleBEAN> cDados;
    private JogoControle jControle = new JogoControle();
    private NotaDeCompraControle notac = new NotaDeCompraControle();
    private NotaDeCompraAPrazoControle napC = new NotaDeCompraAPrazoControle();
    private LucroControle lucroc = new LucroControle();
    private ArrayList<NotaDeCompraPrazoBEAN> napDados;
    private DefaultTableModel dtNota;
    private DefaultTableModel dtPrazos;
    private DefaultTableModel dtNotaPrazo;
    private ArrayList<NotaDeCompraPrazoBEAN> insert = new ArrayList<NotaDeCompraPrazoBEAN>();
    private SimpleDateFormat sdf = new SimpleDateFormat("yyyy-MM-dd");
    private int cod = 0;

    /**
     * Creates new form FRMNotaDeCompra
     */
    public FRMNotaDeCompra() {
        initComponents();
        JogoBEAN jogo = FRMJogo.jogoNota;
        for (NotaDecompraBEAN n : notac.listarALL()) {
            if (n.getJogo().getJoCodigo() == jogo.getJoCodigo()) {
                tpGuia.setSelectedIndex(1);
                JOptionPane.showMessageDialog(null, "Esse jogo ja possui nota de compra CADASTRADA, código da nota:" + n.getNdcCodigo());
            } else {

            }
        }
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpGuia = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jpCompra = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tfQtde = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        tfPrecoTT = new javax.swing.JTextField();
        tfPrecoUnit = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        tfDataCompra = new javax.swing.JFormattedTextField();
        lbCodigoJogo = new javax.swing.JLabel();
        tfChaveJogo2 = new javax.swing.JTextField();
        jPanel3 = new javax.swing.JPanel();
        btCadastrar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jpCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da compra", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Preço Unitario :");

        jLabel9.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel9.setText("Quantidade :");

        tfQtde.setEnabled(false);
        tfQtde.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfQtdeKeyTyped(evt);
            }
        });

        jLabel14.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel14.setText("Preço Total:");

        tfPrecoTT.setEnabled(false);
        tfPrecoTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoTTActionPerformed(evt);
            }
        });

        tfPrecoUnit.setEnabled(false);

        jLabel19.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel19.setText("Data da Compra:");

        try{
            javax.swing.text.MaskFormatter faixa= new javax.swing.text.MaskFormatter("##/##/####");
            tfDataCompra = new javax.swing.JFormattedTextField(faixa);
        }
        catch (Exception e){
        }
        tfDataCompra.setEnabled(false);

        lbCodigoJogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbCodigoJogo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome do Jogo", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tfChaveJogo2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfChaveJogo2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChaveJogo2ActionPerformed(evt);
            }
        });
        tfChaveJogo2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChaveJogo2KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfChaveJogo2KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfChaveJogo2KeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpCompraLayout = new javax.swing.GroupLayout(jpCompra);
        jpCompra.setLayout(jpCompraLayout);
        jpCompraLayout.setHorizontalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfDataCompra, javax.swing.GroupLayout.DEFAULT_SIZE, 84, Short.MAX_VALUE)
                            .addComponent(tfPrecoUnit)
                            .addComponent(tfQtde, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tfPrecoTT, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addComponent(tfChaveJogo2, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbCodigoJogo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(340, 340, 340))
        );
        jpCompraLayout.setVerticalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbCodigoJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChaveJogo2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(tfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(tfPrecoTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(13, 13, 13)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(tfQtde, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPrecoUnit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btCadastrar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btCadastrar.setText("Gravar");
        btCadastrar.setEnabled(false);
        btCadastrar.setMaximumSize(new java.awt.Dimension(73, 23));
        btCadastrar.setMinimumSize(new java.awt.Dimension(73, 23));
        btCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCadastrarActionPerformed(evt);
            }
        });

        jButton7.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton7.setText("Novo dado");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton6.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton6.setText("Fechar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton8.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton8.setText("Cancelar");
        jButton8.setEnabled(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btCadastrar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        tpGuia.addTab("Cadastrar Nota de compra", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 752, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 303, Short.MAX_VALUE)
        );

        tpGuia.addTab("Nota a prazo", jPanel2);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        jLabel1.setText("Nota De Compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(302, 302, 302)
                .addComponent(jLabel1))
            .addComponent(tpGuia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tpGuia))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limparCampos() {
        lbCodigoJogo.setText("...");
        tfPrecoUnit.setText("");
        tfQtde.setText("");
        tfValorEntrada.setText("");
        tfPrecoTT.setText("");
        tfDataCompra.setText("");
        tfNParcelas.setText("");

    }

    private boolean verificaCampos() {
        if (tfPrecoUnit.getText().equals("") || tfQtde.getText().equals("")
                || tfValorEntrada.getText().equals("") || tfPrecoTT.getText().equals("")
                || tfNParcelas.getText().equals("")
                || tfDataCompra.getText().equals("")
                || lbCodigoJogo.getText().equals("...")) {
            return false;
        } else {
            return true;
        }
    }

    private int verificarInserir() {
        int j = 0;
        for (NotaDeCompraPrazoBEAN a : insert) {
            j++;
        }
        System.out.println(j);
        return j;
    }

    private void resultado() {
        insert.clear();
        preencheTabelaPrazos();
        preencheTabelaNota();

        limparCampos();
        JOptionPane.showMessageDialog(null, "Notas CADASTRADAS com sucesso");
    }

    private void cadastroInserir() {
        NotaDecompraBEAN ndc = new NotaDecompraBEAN();
        ndc.setNdcCustoUnitario(Float.parseFloat(tfPrecoUnit.getText()));
        ndc.setNdcQtdComprada(Integer.parseInt(tfQtde.getText()));
        ndc.setNdcEntrada(Float.parseFloat(tfValorEntrada.getText()));
        ndc.setNdcPrecoTotal(Float.parseFloat(tfPrecoTT.getText()));

        try {
            String dataString = tfDataCompra.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
            ndc.setNdcData(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        ndc.setNdcParcelas(Integer.parseInt(tfNParcelas.getText()));

        JogoBEAN jogo = jControle.localizarCodigo(Integer.parseInt(lbCodigoJogo.getText()));
        ndc.setJogo(jogo);
        notac.cadastrar(ndc);

        CaixaBEAN caixa = cCaixa.localizar(1);
        caixa.setCaixaDinheiro(caixa.getCaixaDinheiro() - ndc.getNdcEntrada());
        cCaixa.editar(caixa);

        for (NotaDeCompraPrazoBEAN ndca : insert) {
            NotaDeCompraPrazoBEAN nota = new NotaDeCompraPrazoBEAN();
            nota.setNapData(ndca.getNapData());
            nota.setNapValor(ndca.getNapValor());
            nota.setNapNumParcela(ndca.getNapNumParcela());
            nota.setNapSituacao("Pendente");
            nota.setNota(ndc);
            napC.cadastrar(nota);
        }
        resultado();
    }

    private void tfQtdeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfQtdeKeyTyped
        String caracteres = "0123456789";
        if (!caracteres.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfQtdeKeyTyped

    private void tfPrecoTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoTTActionPerformed

    private void cadastroNormal() {
        NotaDecompraBEAN ndc = new NotaDecompraBEAN();
        ndc.setNdcCustoUnitario(Float.parseFloat(tfPrecoUnit.getText()));
        ndc.setNdcQtdComprada(Integer.parseInt(tfQtde.getText()));
        ndc.setNdcEntrada(Float.parseFloat(tfValorEntrada.getText()));
        ndc.setNdcPrecoTotal(Float.parseFloat(tfPrecoTT.getText()));

        try {
            String dataString = tfDataCompra.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
            ndc.setNdcData(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }

        ndc.setNdcParcelas(Integer.parseInt(tfNParcelas.getText()));
        JogoBEAN jogo = jControle.localizarCodigo(Integer.parseInt(lbCodigoJogo.getText()));
        ndc.setJogo(jogo);
        notac.cadastrar(ndc);

        CaixaBEAN caixa = cCaixa.localizar(1);
        caixa.setCaixaDinheiro(caixa.getCaixaDinheiro() - ndc.getNdcEntrada());
        cCaixa.editar(caixa);

        limparCampos();
        preencheTabelaNota();
    }

    private void preencheTabelaPrazos() {
        dtPrazos = criaTabelaPrazos();
        dtPrazos.addColumn("Num.Parcela");
        dtPrazos.addColumn("Data");
        dtPrazos.addColumn("Preço");

        for (NotaDeCompraPrazoBEAN o : insert) {
            dtPrazos.addRow(new Object[]{o.getNapNumParcela(),
                o.getNapData(), o.getNapValor()});
        }

        tableM.setModel(dtPrazos);
    }

    private DefaultTableModel criaTabelaPrazos() {
        DefaultTableModel dTable2 = new DefaultTableModel() {
            Class[] types = new Class[]{
                java.lang.Integer.class,
                java.lang.String.class,
                java.lang.Float.class,};
            boolean[] canEdit = new boolean[]{
                false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;
        };
    return dTable2;
    }

    private void btCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCadastrarActionPerformed
        int z = verificarInserir();
        if (verificaCampos()) {
            if (lbCodNota.getText().equals("...")) {
                if (z == 0) {
                    cadastroNormal();
                    JOptionPane.showMessageDialog(null, "Nota Cadastrada com sucesso.");
                } else {
                    cadastroInserir();
                }
            } else {
                editar();
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro!Preencha todos os campos.");
        }

    }//GEN-LAST:event_btCadastrarActionPerformed

    private void editar() {
        if (verificaCampos() == true) {
            NotaDecompraBEAN ndc = notac.localizar(Integer.parseInt(lbCodNota.getText()));
            ndc.setNdcCustoUnitario(Float.parseFloat(tfPrecoUnit.getText()));
            ndc.setNdcQtdComprada(Integer.parseInt(tfQtde.getText()));
            ndc.setNdcEntrada(Float.parseFloat(tfValorEntrada.getText()));
            ndc.setNdcPrecoTotal(Float.parseFloat(tfPrecoTT.getText()));
            ndc.setNdcParcelas(Integer.parseInt(tfNParcelas.getText()));
            try {
                String dataString = tfDataCompra.getText();
                DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
                ndc.setNdcData(data);
            } catch (ParseException e) {
                e.printStackTrace();
            }
            JogoBEAN jogo = jControle.localizarCodigo(Integer.parseInt(lbCodigoJogo.getText()));
            ndc.setJogo(jogo);
            boolean retorno = notac.editar(ndc);
            if (retorno == true) {
                JOptionPane.showMessageDialog(null, "Jogo MODIFICADO com sucesso");
                this.preencheTabelaNota();
                this.preencheTabelaPrazos();
                this.limparCampos();
            } else {
                JOptionPane.showMessageDialog(null, "ERRO na EDIÇÃO");
            }

        } else {
            JOptionPane.showMessageDialog(null, "Erro! Insira todos os valores");
        }
    }
    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        this.dispose();
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed

    }//GEN-LAST:event_jButton7ActionPerformed

    private void tfChaveJogo2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChaveJogo2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChaveJogo2ActionPerformed

    private void tfChaveJogo2KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogo2KeyPressed

    }//GEN-LAST:event_tfChaveJogo2KeyPressed

    private void tfChaveJogo2KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogo2KeyReleased
        int c;
        if (tfChaveJogo.getText().equals("")) {
            c = 0;
        } else {
            c = Integer.parseInt(tfChaveJogo.getText());
        }
        povoaTabelaJogo(c);
    }//GEN-LAST:event_tfChaveJogo2KeyReleased

    private void tfChaveJogo2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogo2KeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfChaveJogo2KeyTyped

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMNotaDeCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMNotaDeCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMNotaDeCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);

        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMNotaDeCompra.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMNotaDeCompra().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btCadastrar;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jpCompra;
    private javax.swing.JLabel lbCodigoJogo;
    private javax.swing.JTextField tfChaveJogo2;
    private javax.swing.JFormattedTextField tfDataCompra;
    private javax.swing.JTextField tfPrecoTT;
    private javax.swing.JTextField tfPrecoUnit;
    private javax.swing.JTextField tfQtde;
    private javax.swing.JTabbedPane tpGuia;
    // End of variables declaration//GEN-END:variables
}
