/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ControleUser;

import Modelo.UserBEAN;
import Modelo.UserDAO;
import java.awt.Color;
import static java.awt.Color.BLACK;
import static java.awt.Color.GRAY;

import java.util.ArrayList;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author LUCASP
 */
public class FRMPrincipalAdm extends javax.swing.JFrame {

    private ArrayList<UserBEAN> userD;
    private DefaultTableModel tbUsers;
    ControleUser ct = new ControleUser();

    /**
     * Creates new form FRMAdm
     */
    public FRMPrincipalAdm() {
        initComponents();
        setResizable(false);
        this.preencheTabela();

    }

    private void preencheTabela() {
        tbUsers = this.criaTabela();
        tbUsers.addColumn("Código");
        tbUsers.addColumn("Nome");
        tbUsers.addColumn("CPF");
        userD = ct.ListarALL();

        for (UserBEAN d : userD) {
            tbUsers.addRow(new Object[]{
                d.getCodigo(),
                d.getNome(),
                d.getCpf(),});
        }
        //set o modelo da tabela
        tbPesquisa.setModel(tbUsers);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        jtbPesquisa = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tfNomeFun = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tfEnderecoFun = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfNomeUserFun = new javax.swing.JTextField();
        jbCadastrarFun = new javax.swing.JButton();
        jbEditarFun = new javax.swing.JToggleButton();
        jbLocalizarFun = new javax.swing.JToggleButton();
        jbExcluirFun = new javax.swing.JToggleButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        tfNPFun = new javax.swing.JFormattedTextField();
        tfCpfFun = new javax.swing.JFormattedTextField();
        tfTelefoneFun = new javax.swing.JFormattedTextField();
        tfIdadeFun = new javax.swing.JFormattedTextField();
        jLabel11 = new javax.swing.JLabel();
        lbCodigo = new javax.swing.JLabel();
        tfSenhaUserFun = new javax.swing.JPasswordField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbPesquisa = new javax.swing.JTable();
        tfPesquisaFun = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        btSair = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Administrador");
        getContentPane().setLayout(null);

        jtbPesquisa.setBackground(new java.awt.Color(204, 204, 255));
        jtbPesquisa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jtbPesquisa.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jtbPesquisaFocusGained(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(204, 204, 255));

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Nome de usuário:");

        jbCadastrarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JLabelFun.png"))); // NOI18N
        jbCadastrarFun.setText("Cadastrar");
        jbCadastrarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCadastrarFunActionPerformed(evt);
            }
        });

        jbEditarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonEdit.png"))); // NOI18N
        jbEditarFun.setText("Editar");
        jbEditarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarFunActionPerformed(evt);
            }
        });

        jbLocalizarFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonConsultarCliente.png"))); // NOI18N
        jbLocalizarFun.setText("Localizar");
        jbLocalizarFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLocalizarFunActionPerformed(evt);
            }
        });

        jbExcluirFun.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonDeletarFun.png"))); // NOI18N
        jbExcluirFun.setText("Excluir");
        jbExcluirFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirFunActionPerformed(evt);
            }
        });

        jLabel4.setText("Senha:");

        jLabel5.setText("CPF:");

        jLabel6.setText("Telefone:");

        jLabel7.setText("Idade:");

        jLabel10.setText("NIS/PIS:");

        try{
            javax.swing.text.MaskFormatter nis= new javax.swing.text.MaskFormatter("###.#####.##-#");
            tfNPFun = new javax.swing.JFormattedTextField(nis);
        }
        catch (Exception e){
        }

        try{
            javax.swing.text.MaskFormatter cpf= new javax.swing.text.MaskFormatter("###.###.###-##");
            tfCpfFun = new javax.swing.JFormattedTextField(cpf);
        }
        catch (Exception e){
        }

        try{
            javax.swing.text.MaskFormatter tel= new javax.swing.text.MaskFormatter("(##)# ####-####");
            tfTelefoneFun = new javax.swing.JFormattedTextField(tel);
        }
        catch (Exception e){
        }

        try{
            javax.swing.text.MaskFormatter idade= new javax.swing.text.MaskFormatter("##");
            tfIdadeFun = new javax.swing.JFormattedTextField(idade);
        }
        catch (Exception e){
        }

        jLabel11.setText("Código:");

        lbCodigo.setText("...");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel10, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(0, 17, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNomeUserFun, javax.swing.GroupLayout.DEFAULT_SIZE, 184, Short.MAX_VALUE)
                            .addComponent(tfNPFun)
                            .addComponent(tfCpfFun)
                            .addComponent(tfTelefoneFun)
                            .addComponent(lbCodigo)
                            .addComponent(tfSenhaUserFun))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addGap(65, 65, 65)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(tfEnderecoFun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(tfNomeFun, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 183, Short.MAX_VALUE)
                            .addComponent(tfIdadeFun))
                        .addGap(72, 72, 72))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jbCadastrarFun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbEditarFun, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jbLocalizarFun)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jbExcluirFun)
                        .addGap(32, 32, 32))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(tfNomeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(tfIdadeFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(6, 6, 6)
                        .addComponent(tfEnderecoFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfCpfFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNPFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfTelefoneFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNomeUserFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfSenhaUserFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lbCodigo))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jbEditarFun)
                        .addComponent(jbLocalizarFun)
                        .addComponent(jbExcluirFun))
                    .addComponent(jbCadastrarFun))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        jtbPesquisa.addTab("Gerenciar usuários", jPanel1);

        tbPesquisa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tbPesquisa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbPesquisaMouseClicked(evt);
            }
        });
        tbPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tbPesquisaKeyReleased(evt);
            }
        });
        jScrollPane1.setViewportView(tbPesquisa);

        tfPesquisaFun.setForeground(new java.awt.Color(204, 204, 204));
        tfPesquisaFun.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                tfPesquisaFunFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                tfPesquisaFunFocusLost(evt);
            }
        });
        tfPesquisaFun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPesquisaFunActionPerformed(evt);
            }
        });
        tfPesquisaFun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPesquisaFunKeyTyped(evt);
            }
        });

        jLabel8.setText("Nome:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 431, Short.MAX_VALUE)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel8)
                .addGap(39, 39, 39)
                .addComponent(tfPesquisaFun, javax.swing.GroupLayout.PREFERRED_SIZE, 288, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(78, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfPesquisaFun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(88, 88, 88))
        );

        jtbPesquisa.addTab("Consultar Funcionários", jPanel2);

        getContentPane().add(jtbPesquisa);
        jtbPesquisa.setBounds(30, 0, 440, 400);

        btSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonLogin.png"))); // NOI18N
        btSair.setText("Sair");
        btSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSairActionPerformed(evt);
            }
        });
        getContentPane().add(btSair);
        btSair.setBounds(480, 10, 80, 20);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonAdm.png"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(0, 0, 50, 40);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Interface gráfica/back2.png"))); // NOI18N
        getContentPane().add(jLabel12);
        jLabel12.setBounds(-20, -10, 640, 440);

        setSize(new java.awt.Dimension(579, 438));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSairActionPerformed
        FRMLogin login = new FRMLogin();
        this.dispose();
        login.setVisible(true);        // TODO add your handling code here:
    }//GEN-LAST:event_btSairActionPerformed

    private void jtbPesquisaFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jtbPesquisaFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_jtbPesquisaFocusGained

    private void tfPesquisaFunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPesquisaFunKeyTyped
        readJTableForNome(tfPesquisaFun.getText());
    }//GEN-LAST:event_tfPesquisaFunKeyTyped

    private void tfPesquisaFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPesquisaFunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPesquisaFunActionPerformed

    private void tfPesquisaFunFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPesquisaFunFocusLost
        tfPesquisaFun.setForeground(GRAY);
    }//GEN-LAST:event_tfPesquisaFunFocusLost

    private void tfPesquisaFunFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_tfPesquisaFunFocusGained
        tfPesquisaFun.setText("");
        tfPesquisaFun.setForeground(BLACK);
    }//GEN-LAST:event_tfPesquisaFunFocusGained

    private void tbPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tbPesquisaKeyReleased

    }//GEN-LAST:event_tbPesquisaKeyReleased

    private void tbPesquisaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbPesquisaMouseClicked
        jbCadastrarFun.setEnabled(false);
        jtbPesquisa.setSelectedIndex(0);
        if (tbPesquisa.getSelectedRow() != -1) {
            lbCodigo.setText((String) tbPesquisa.getValueAt(tbPesquisa.getSelectedRow(), 0).toString());
            tfNomeFun.setText(tbPesquisa.getValueAt(tbPesquisa.getSelectedRow(), 1).toString());
            tfCpfFun.setText((String) tbPesquisa.getValueAt(tbPesquisa.getSelectedRow(), 2).toString());
        }
    }//GEN-LAST:event_tbPesquisaMouseClicked

    private void jbExcluirFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirFunActionPerformed
        if (lbCodigo.getText().equals("...")) {
            JOptionPane.showMessageDialog(null, "É preciso ter localizado um usuário!");
        } else {
            ct.excluir(Integer.parseInt(lbCodigo.getText()));
            limpaCampos();
            this.preencheTabela();

        }
    }//GEN-LAST:event_jbExcluirFunActionPerformed

    private void jbEditarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarFunActionPerformed
        if (lbCodigo.getText().equals("...")) {
            JOptionPane.showMessageDialog(null, "É preciso selecionar um funcionário na tabela de consulta");
        } else if (tfNomeFun.getText().equals("") || tfIdadeFun.getText().equals("") || tfEnderecoFun.getText().equals("") || tfCpfFun.getText().equals("")
                || tfNPFun.getText().equals("") || tfNomeUserFun.getText().equals("") || tfSenhaUserFun.getText().equals("") || tfTelefoneFun.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios");
        } else {
            ct.editar(tfNomeFun.getText(), Integer.parseInt(tfIdadeFun.getText()), tfEnderecoFun.getText(), tfCpfFun.getText(),
                    tfNPFun.getText(), tfNomeUserFun.getText(), tfSenhaUserFun.getText(), tfTelefoneFun.getText());
            limpaCampos();
            this.preencheTabela();
            jbCadastrarFun.setEnabled(true);
        }
    }//GEN-LAST:event_jbEditarFunActionPerformed

    private void jbCadastrarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCadastrarFunActionPerformed
        if (tfNomeFun.getText().equals("") || tfIdadeFun.getText().equals("") || tfEnderecoFun.getText().equals("") || tfCpfFun.getText().equals("")
                || tfNPFun.getText().equals("") || tfNomeUserFun.getText().equals("") || tfSenhaUserFun.getText().equals("") || tfTelefoneFun.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Todos os campos são obrigatórios");
        } else {
            ct.cadastrar(tfNomeFun.getText(), Integer.parseInt(tfIdadeFun.getText()), tfEnderecoFun.getText(), tfCpfFun.getText(),
                    tfNPFun.getText(), tfNomeUserFun.getText(), tfSenhaUserFun.getText(), tfTelefoneFun.getText());
            this.preencheTabela();
            limpaCampos();
        }
    }//GEN-LAST:event_jbCadastrarFunActionPerformed

    private void jbLocalizarFunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLocalizarFunActionPerformed
        jtbPesquisa.setSelectedIndex(1);
    }//GEN-LAST:event_jbLocalizarFunActionPerformed
    public void limpaCampos() {
        tfNomeFun.setText("");
        tfIdadeFun.setText("");
        tfEnderecoFun.setText("");
        tfCpfFun.setText("");
        tfNPFun.setText("");
        tfNomeUserFun.setText("");
        tfSenhaUserFun.setText("");
        tfTelefoneFun.setText("");
        lbCodigo.setText("...");
    }

    private void readJTableForNome(String funNome) {
        DefaultTableModel model = (DefaultTableModel) tbPesquisa.getModel();

        model.setNumRows(0);
        UserDAO dao = new UserDAO();

        for (UserBEAN d : dao.readForNome(funNome)) {
            tbUsers.addRow(new Object[]{
                d.getCodigo(),
                d.getNome(),
                d.getCpf(),});

        }
        //set o modelo da tabela
        tbPesquisa.setModel(tbUsers);
    }

    private DefaultTableModel criaTabela() {
        //sempre que usar JTable é necessário ter um DefaulttableModel
        DefaultTableModel tbUsers = new DefaultTableModel() {
            //Define o tipo dos campos (coluna) na mesma ordem que as colunas foram criadas
            Class[] types = new Class[]{
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class,};
            //define se os campos podem ser editados na propria tabela
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;

        };
        //retorna o DefaultTableModel
    return tbUsers;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMPrincipalAdm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMPrincipalAdm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSair;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbCadastrarFun;
    private javax.swing.JToggleButton jbEditarFun;
    private javax.swing.JToggleButton jbExcluirFun;
    private javax.swing.JToggleButton jbLocalizarFun;
    private javax.swing.JTabbedPane jtbPesquisa;
    private javax.swing.JLabel lbCodigo;
    private javax.swing.JTable tbPesquisa;
    private javax.swing.JFormattedTextField tfCpfFun;
    private javax.swing.JTextField tfEnderecoFun;
    private javax.swing.JFormattedTextField tfIdadeFun;
    private javax.swing.JFormattedTextField tfNPFun;
    private javax.swing.JTextField tfNomeFun;
    private javax.swing.JTextField tfNomeUserFun;
    private javax.swing.JTextField tfPesquisaFun;
    private javax.swing.JPasswordField tfSenhaUserFun;
    private javax.swing.JFormattedTextField tfTelefoneFun;
    // End of variables declaration//GEN-END:variables

}
