/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.ClienteControle;
import Controle.DevolucaoControle;
import Controle.JogoControle;
import Controle.LocacaoControle;
import Controle.AutoCompleteComboBox;
import Modelo.ClienteBEAN;
import Modelo.DevolucaoBEAN;
import Modelo.JogoBEAN;
import Modelo.LocacaoBEAN;
import java.util.ArrayList;
import java.util.Date;
import java.util.Vector;
import javax.swing.DefaultCellEditor;
import javax.swing.JComboBox;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import org.apache.commons.lang.RandomStringUtils;

/**
 *
 * @author LUCASP
 */
public class FRMTransacao extends javax.swing.JFrame {

    ClienteControle contCli = new ClienteControle();
    JogoControle contJog = new JogoControle();
    LocacaoControle contLoc = new LocacaoControle();
    DevolucaoControle contDev = new DevolucaoControle();
    ArrayList<ClienteBEAN> tcli = new ArrayList<>();
    ArrayList<JogoBEAN> tJog = new ArrayList<>();
    ArrayList<LocacaoBEAN> tLoc = new ArrayList<>();
    JComboBox<String> combo = new JComboBox<>();
    private DefaultTableModel modelJogo;
    private DefaultTableModel model;

    private DefaultTableModel modelLoc;
    ArrayList<String> elementsCli = new ArrayList<>();
    ArrayList<String> elementsJog = new ArrayList<>();

    ClienteBEAN clienteSelecionado;
    JogoBEAN jogoSelecionado;
    LocacaoBEAN locSelecionada;

    private void preencheTabelaCli(ArrayList<ClienteBEAN> cli) {
        tcli = cli;
        model.setRowCount(0);
        for (ClienteBEAN dado : cli) {

            model.addRow(new Object[]{dado.getNome(), dado.getCpf(), dado.getTelefone(), dado.getEndereco()});

        }

        for (ClienteBEAN c : tcli) {
            elementsCli.add(c.getNome());
        }

        for (JogoBEAN c : tJog) {
            elementsJog.add(c.getJoNome());
        }

        JComboBox comboBoxCli = new AutoCompleteComboBox(elementsCli.toArray());
        cbCliente.setModel(comboBoxCli.getModel());
        cbCliente.setEditor(comboBoxCli.getEditor());
        cbCliente.setEditable(true);

        JComboBox comboBoxJog = new AutoCompleteComboBox(elementsJog.toArray());
        cbJogo.setModel(comboBoxJog.getModel());
        cbJogo.setEditor(comboBoxJog.getEditor());
        cbJogo.setEditable(true);

    }

    private void preencheTabelaJog(ArrayList<JogoBEAN> jog) {
        tJog = jog;
        modelJogo.setRowCount(0);
        for (JogoBEAN dado : jog) {
            if (dado.getJoDisponibilidade() == 0) {
                modelJogo.addRow(new Object[]{dado.getJoNome(), dado.getJoTipo(), dado.getJoFaixaEtaria(), dado.getJoQtd(),
                    dado.getJoPrecoPadrao(), "Disponível"});
            } else {
                modelJogo.addRow(new Object[]{dado.getJoNome(), dado.getJoTipo(), dado.getJoFaixaEtaria(), dado.getJoQtd(),
                    dado.getJoPrecoPadrao(), "Indisponível"});
            }

        }

    }

    private void preencheTabelaLoc(ArrayList<LocacaoBEAN> loc) {
        tLoc = loc;
        modelLoc.setRowCount(0);
        for (LocacaoBEAN dado : loc) {
            modelLoc.addRow(new Object[]{dado.getData(), contJog.localizarCodigo(dado.getLoc_jogCodigo()), dado.getValor()});
        }

    }

    /**
     * Creates new form FRMTransacao
     */
    public FRMTransacao() {
        initComponents();
        model = (DefaultTableModel) tbCliente.getModel();
        modelJogo = (DefaultTableModel) tbJogo.getModel();
        modelLoc = (DefaultTableModel) tbLoc.getModel();
        tcli = contCli.listarALL();
        tJog = contJog.listarALL();
        //tLoc = contLoc.listarALL();

        String disp = "Disponível";
        String indisp = "Indisponível";
        combo.addItem(disp);
        combo.addItem(indisp);

        TableColumn tc2 = tbJogo.getColumnModel().getColumn(5);
        tc2.setCellEditor(new DefaultCellEditor(combo));

        preencheTabelaCli(tcli);

        preencheTabelaJog(tJog);
        setResizable(false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpGuia = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        lbPrecoBase = new javax.swing.JLabel();
        btPesquisarCliente1 = new javax.swing.JToggleButton();
        jLabel11 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btAlugar = new javax.swing.JButton();
        btPesquisarJogo1 = new javax.swing.JToggleButton();
        jLabel19 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tfPrecoAluguel = new javax.swing.JFormattedTextField();
        jLabel20 = new javax.swing.JLabel();
        lbJogo = new javax.swing.JLabel();
        lbCliente = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jPanel4 = new javax.swing.JPanel();
        jLabel21 = new javax.swing.JLabel();
        btPesquisarCliente2 = new javax.swing.JToggleButton();
        btDevolver = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbLoc = new javax.swing.JTable();
        lbCliDev = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel22 = new javax.swing.JLabel();
        tfMulta = new javax.swing.JTextField();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        lbPrecoFinal = new javax.swing.JLabel();
        btCalc = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbCliente = new javax.swing.JTable();
        cbCliente = new javax.swing.JComboBox<>();
        btPesquisaCli4 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        cbJogo = new javax.swing.JComboBox<>();
        btPesquisaJogo = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbJogo = new javax.swing.JTable();
        btAtualizar = new javax.swing.JButton();
        btVoltar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        tfPrecoVenda = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Transação");
        getContentPane().setLayout(null);

        lbPrecoBase.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        lbPrecoBase.setText("...");

        btPesquisarCliente1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonPesquisarConsutar.png"))); // NOI18N
        btPesquisarCliente1.setText("Pesquisar");
        btPesquisarCliente1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCliente1ActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setText("Jogo:");

        jLabel3.setText("R$/7d");

        btAlugar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btAlugar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonAluguel.png"))); // NOI18N
        btAlugar.setText("Alugar");
        btAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAlugarActionPerformed(evt);
            }
        });

        btPesquisarJogo1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonPesquisarConsutar.png"))); // NOI18N
        btPesquisarJogo1.setText("Selecionar");
        btPesquisarJogo1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarJogo1ActionPerformed(evt);
            }
        });

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel19.setText("Cliente:");

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel12.setText("Preço base (Aluguel) - R$ :");

        try{
            javax.swing.text.MaskFormatter preco= new javax.swing.text.MaskFormatter("###.##");
            tfPrecoVenda = new javax.swing.JFormattedTextField(preco);
        }
        catch (Exception e){
        }
        tfPrecoAluguel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfPrecoAluguelActionPerformed(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel20.setText("Preço aluguel:");

        lbJogo.setText("....");

        lbCliente.setText("...");

        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addComponent(jLabel11)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(lbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 233, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(btPesquisarJogo1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbPrecoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btPesquisarCliente1, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfPrecoAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(254, 254, 254)
                        .addComponent(btAlugar, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(41, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jSeparator1)
                        .addGap(70, 70, 70))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel11)
                                    .addComponent(lbJogo)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel19)
                                    .addComponent(lbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btPesquisarJogo1)
                            .addComponent(btPesquisarCliente1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 58, Short.MAX_VALUE)))
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(tfPrecoAluguel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(lbPrecoBase)
                    .addComponent(jLabel12))
                .addGap(35, 35, 35)
                .addComponent(btAlugar)
                .addGap(53, 53, 53))
        );

        tpGuia.addTab("Aluguel", jPanel3);

        jLabel21.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel21.setText("Cliente:");

        btPesquisarCliente2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonPesquisarConsutar.png"))); // NOI18N
        btPesquisarCliente2.setText("Pesquisar");
        btPesquisarCliente2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarCliente2ActionPerformed(evt);
            }
        });

        btDevolver.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btDevolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonDevolver.png"))); // NOI18N
        btDevolver.setText("Devolver");
        btDevolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btDevolverActionPerformed(evt);
            }
        });

        tbLoc.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data - Aluguel", "Jogo", "Preço Prático"
            }
        ));
        tbLoc.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbLocMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbLoc);

        lbCliDev.setText("...");

        jSeparator2.setOrientation(javax.swing.SwingConstants.VERTICAL);

        jLabel22.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel22.setText("Aluguéis:");

        tfMulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfMultaActionPerformed(evt);
            }
        });

        jLabel23.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel23.setText("Multa:");

        jLabel24.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel24.setText("Preço Final:");

        lbPrecoFinal.setText("...");

        btCalc.setText("Calcular preço final");
        btCalc.setEnabled(false);
        btCalc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCalcActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addComponent(btDevolver, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(237, 237, 237))
                        .addGroup(jPanel4Layout.createSequentialGroup()
                            .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(btPesquisarCliente2, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(btCalc))
                                .addGroup(jPanel4Layout.createSequentialGroup()
                                    .addComponent(jLabel24)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lbPrecoFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(58, 58, 58)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel21)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbCliDev, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(200, 200, 200)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel22))
                .addGap(37, 37, 37))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(21, 21, 21)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel21)
                            .addComponent(lbCliDev)))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(jLabel22)))
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(btPesquisarCliente2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btDevolver)
                .addGap(50, 50, 50))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(tfMulta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel23)
                            .addComponent(btCalc))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel24)
                            .addComponent(lbPrecoFinal)))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 178, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );

        tpGuia.addTab("Devolução", jPanel4);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel4.setText("Nome:");

        tbCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "CPF", "Telefone", "Endereço"
            }
        ));
        tbCliente.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbClienteMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbCliente);

        cbCliente.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btPesquisaCli4.setText("Localizar");
        btPesquisaCli4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaCli4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 470, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisaCli4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(cbCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisaCli4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        tpGuia.addTab("Pesquisa - Cliente", jPanel1);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Nome:");

        cbJogo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        btPesquisaJogo.setText("Localizar");
        btPesquisaJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisaJogoActionPerformed(evt);
            }
        });

        tbJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "Tipo", "Faixa Etária", "Qtd", "Preço Base", "Disponibilidade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbJogoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbJogo);

        btAtualizar.setText("Mudar disponibilidade");
        btAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAtualizarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(cbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 308, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btPesquisaJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 585, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(231, 231, 231)
                        .addComponent(btAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(43, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(cbJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisaJogo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btAtualizar)
                .addGap(30, 30, 30))
        );

        tpGuia.addTab("Pesquisa - Jogo", jPanel5);

        getContentPane().add(tpGuia);
        tpGuia.setBounds(10, 20, 680, 320);

        btVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Botões/JButtonLogin.png"))); // NOI18N
        btVoltar.setText("Voltar");
        btVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVoltarActionPerformed(evt);
            }
        });
        getContentPane().add(btVoltar);
        btVoltar.setBounds(610, 10, 80, 20);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Visao/icons/Interface gráfica/back2.png"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(-10, -10, 730, 410);

        tfPrecoVenda.setText("jTextField1");
        getContentPane().add(tfPrecoVenda);
        tfPrecoVenda.setBounds(440, 10, 59, 20);

        setSize(new java.awt.Dimension(723, 419));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVoltarActionPerformed
        FRMPrincipalFun fun = new FRMPrincipalFun();
        this.dispose();
        fun.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_btVoltarActionPerformed

    private void btAlugarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAlugarActionPerformed
        if (clienteSelecionado != null && jogoSelecionado != null) {
            LocacaoControle locCon = new LocacaoControle();
            LocacaoBEAN l = new LocacaoBEAN();
            l.setValor(Float.parseFloat("" + tfPrecoAluguel.getText()));
            Date utilDate = new Date();
            java.sql.Date data = new java.sql.Date(utilDate.getTime());
            l.setData(data);
            l.setLoc_cliCodigo(clienteSelecionado.getCod());
            l.setLoc_jogCodigo(jogoSelecionado.getJoCodigo());
            l.setLoc_funCodigo(FRMLogin.user.getFunCodigo());
            locCon.cadastrar(l);
            JOptionPane.showMessageDialog(null, "Locação realizada com sucesso!");
            clienteSelecionado = null;
            jogoSelecionado = null;
            lbJogo.setText("...");
            lbCliente.setText("...");
            tfPrecoAluguel.setText("");
            lbPrecoBase.setText("");

        } else {
            JOptionPane.showMessageDialog(null, "Um jogo e um cliente devem ser selecionados!");
        }
    }//GEN-LAST:event_btAlugarActionPerformed

    private void btDevolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btDevolverActionPerformed
        if (locSelecionada != null && clienteSelecionado != null) {

            DevolucaoBEAN dev = new DevolucaoBEAN();
            if (tfMulta.equals("")) {

                dev.setMulta(0);
                JOptionPane.showMessageDialog(null, "Insira apenas números na multa!");

            } else {
                dev.setMulta(Float.parseFloat("" + tfMulta.getText()));
                dev.setDev_loCodigo(locSelecionada.getCod());
                dev.setDev_funCodigo(FRMLogin.user.getFunCodigo());
                Date utilDate = new Date();
                java.sql.Date data = new java.sql.Date(utilDate.getTime());
                dev.setDataDev(data);
                dev.setValor(dev.getMulta() + locSelecionada.getValor());
                dev.setNf("" + RandomStringUtils.randomAscii(10));
                contDev.cadastrar(dev);
                //contLoc.remover(""+locSelecionada.getCod());
                JOptionPane.showMessageDialog(null, "Devolução realizada com sucesso!");
                lbCliDev.setText("...");
                lbPrecoFinal.setText("...");
                tfMulta.setText("");
                modelLoc.setRowCount(0);
                btCalc.setEnabled(false);
                clienteSelecionado = null;
                locSelecionada = null;
            }

        } else {
            JOptionPane.showMessageDialog(null, "Um cliente e um aluguel devem ser selecionados!");
        }
    }//GEN-LAST:event_btDevolverActionPerformed

    private void tfPrecoAluguelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfPrecoAluguelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfPrecoAluguelActionPerformed

    private void btPesquisarJogo1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarJogo1ActionPerformed
        tpGuia.setSelectedIndex(3);
    }//GEN-LAST:event_btPesquisarJogo1ActionPerformed

    private void btPesquisarCliente1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCliente1ActionPerformed

        tpGuia.setSelectedIndex(2);
    }//GEN-LAST:event_btPesquisarCliente1ActionPerformed

    private void tbClienteMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbClienteMouseClicked

        clienteSelecionado = tcli.get(tbCliente.getSelectedRow());
        tLoc = contLoc.localizarCli(clienteSelecionado.getCod());
        preencheTabelaLoc(tLoc);
        JOptionPane.showMessageDialog(null, "Cliente selecionado");
        lbCliente.setText(clienteSelecionado.getNome().toString());
        lbCliDev.setText(clienteSelecionado.getNome().toString());

    }//GEN-LAST:event_tbClienteMouseClicked

    private void btPesquisaCli4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaCli4ActionPerformed

        model.setRowCount(0);
        System.out.println(cbCliente.getSelectedItem().toString());
        preencheTabelaCli(contCli.localizarNome(cbCliente.getSelectedItem().toString()));
    }//GEN-LAST:event_btPesquisaCli4ActionPerformed

    private void btPesquisaJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisaJogoActionPerformed
        model.setRowCount(0);
        System.out.println(cbJogo.getSelectedItem().toString());
        preencheTabelaJog(contJog.localizarNome(cbJogo.getSelectedItem().toString()));
    }//GEN-LAST:event_btPesquisaJogoActionPerformed

    private void tbJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbJogoMouseClicked

        jogoSelecionado = tJog.get(tbJogo.getSelectedRow());
        JOptionPane.showMessageDialog(null, "Jogo selecionado");
        lbJogo.setText(jogoSelecionado.getJoNome().toString());
        lbPrecoBase.setText("" + jogoSelecionado.getJoPrecoPadrao() / 10);

    }//GEN-LAST:event_tbJogoMouseClicked

    public void atualizaValores(JogoBEAN l) {

        //obtém valores da table para atualizar no banco de dados
        try {
            //transforma os valores de cada row em um vetor
            Vector v = (Vector) modelJogo.getDataVector().elementAt(tbJogo.getSelectedRow());

            //transforma os valores de cada coluna em uma instância no array Object
            Object[] o = v.toArray();

            //l.setJoCodigo(tcli.get(tbJogo.getSelectedRow()).getCod());
            if (((String) o[5]).equals("Disponível")) {
                l.setJoDisponibilidade(0);
                JOptionPane.showMessageDialog(null, "Jogo disponibilizado!");
            } else {
                l.setJoDisponibilidade(1);
                JOptionPane.showMessageDialog(null, "Disponibilidade retirada!");
            }

            //controle.atualizar(l);
            contJog.editarDisponibilidade(l);

        } catch (ArrayIndexOutOfBoundsException e) {

            JOptionPane.showMessageDialog(null, "Selecione um jogo!");
            //e.printStackTrace();

        } catch (java.lang.NullPointerException e) {
            JOptionPane.showMessageDialog(null, "Selecione um jogo!");
            //e.printStackTrace();
        }

    }
    private void btAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAtualizarActionPerformed
        //cria um novo objeto para receber valores da row selecionada

        atualizaValores(jogoSelecionado);
    }//GEN-LAST:event_btAtualizarActionPerformed

    private void tfMultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfMultaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfMultaActionPerformed

    private void btPesquisarCliente2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarCliente2ActionPerformed
        tpGuia.setSelectedIndex(2);
    }//GEN-LAST:event_btPesquisarCliente2ActionPerformed

    private void tbLocMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbLocMouseClicked
        locSelecionada = tLoc.get(tbLoc.getSelectedRow());
        JOptionPane.showMessageDialog(null, "Aluguel selecionado");
        btCalc.setEnabled(true);

    }//GEN-LAST:event_tbLocMouseClicked

    private void btCalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCalcActionPerformed
        lbPrecoFinal.setText("R$ " + (Float.parseFloat("" + tfMulta.getText()) + locSelecionada.getValor()));
    }//GEN-LAST:event_btCalcActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMTransacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMTransacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAlugar;
    private javax.swing.JButton btAtualizar;
    private javax.swing.JButton btCalc;
    private javax.swing.JButton btDevolver;
    private javax.swing.JButton btPesquisaCli4;
    private javax.swing.JButton btPesquisaJogo;
    private javax.swing.JToggleButton btPesquisarCliente1;
    private javax.swing.JToggleButton btPesquisarCliente2;
    private javax.swing.JToggleButton btPesquisarJogo1;
    private javax.swing.JButton btVoltar;
    private javax.swing.JComboBox<String> cbCliente;
    private javax.swing.JComboBox<String> cbJogo;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel lbCliDev;
    private javax.swing.JLabel lbCliente;
    private javax.swing.JLabel lbJogo;
    private javax.swing.JLabel lbPrecoBase;
    private javax.swing.JLabel lbPrecoFinal;
    private javax.swing.JTable tbCliente;
    private javax.swing.JTable tbJogo;
    private javax.swing.JTable tbLoc;
    private javax.swing.JTextField tfMulta;
    private javax.swing.JFormattedTextField tfPrecoAluguel;
    private javax.swing.JTextField tfPrecoVenda;
    private javax.swing.JTabbedPane tpGuia;
    // End of variables declaration//GEN-END:variables
}
