/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Visao;

import Controle.CaixaControle;
import Controle.CategoriaControle;
import Controle.ClienteControle;
import Controle.ConsoleControle;
import Controle.DevolucaoControle;
import Controle.JogoControle;
import Controle.JogoLocacaoControle;
import Controle.JogoVendaControle;
import Controle.LocacaoControle;
import Controle.LucroControle;
import Controle.VendaAPrazoControle;
import Controle.VendaControle;
import Controle.VendedorControle;
import Modelo.CaixaBEAN;
import Modelo.ClienteBEAN;
import Modelo.JogoBEAN;
import Modelo.JogoVendaBEAN;
import Modelo.JogoVendaPK;
import Modelo.VendaAPrazoBEAN;
import Modelo.VendaBEAN;
import Modelo.VendedorBEAN;
import java.text.DateFormat;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alef
 */
public class FRMVendaNova extends javax.swing.JFrame {

    private final String numeros = "0123456789";
    private final String pct = "0123456789.";
    private DefaultTableModel modelJogo;
    private DefaultTableModel modelCarro;
    private DefaultTableModel modelDev;
    private DefaultTableModel modelPrazo;
    private JogoControle contJog = new JogoControle();
    private ClienteControle contCli = new ClienteControle();
    private ConsoleControle cControle = new ConsoleControle();
    private CategoriaControle catControle = new CategoriaControle();
    private VendedorControle cVend = new VendedorControle();
    private CaixaControle cCaixa = new CaixaControle();
    private LucroControle cLucro = new LucroControle();
    private VendaControle contVenda = new VendaControle();
    private VendaAPrazoControle contVendaPrazo = new VendaAPrazoControle();
    private DevolucaoControle contDev = new DevolucaoControle();
    private JogoVendaControle cJV = new JogoVendaControle();
    private ArrayList<JogoBEAN> jogoList = contJog.listarALL();
    private ArrayList<JogoBEAN> insertJogo = new ArrayList<JogoBEAN>();
    private ArrayList<VendaAPrazoBEAN> insertData = new ArrayList<VendaAPrazoBEAN>();

    /**
     * Creates new form FRMVendaNova
     */
    public FRMVendaNova() {
        initComponents();
        this.setLocationRelativeTo(null);
        setResizable(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        tpGuia = new javax.swing.JTabbedPane();
        jPanel12 = new javax.swing.JPanel();
        jPanel14 = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        tfDataCompra = new javax.swing.JFormattedTextField();
        lbVendedorCod1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableJogo = new javax.swing.JTable();
        tfChaveJogo = new javax.swing.JTextField();
        btAddJogo = new javax.swing.JButton();
        btRemoveJogo = new javax.swing.JButton();
        btFechamento = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        tableCarrinho = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jpCompra = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        tfPrecoPago = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        tfTroco = new javax.swing.JTextField();
        tfCliente = new javax.swing.JTextField();
        lbCliNome = new javax.swing.JLabel();
        lbPrecoTT = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        btGravarVenda = new javax.swing.JButton();
        btVendaPrazo = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jpCompra1 = new javax.swing.JPanel();
        btGeraParcela = new javax.swing.JButton();
        jScrollPane8 = new javax.swing.JScrollPane();
        tableParcelas = new javax.swing.JTable();
        btLimpar = new javax.swing.JButton();
        tfValorEntrada1 = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        tfNParcelas1 = new javax.swing.JTextField();
        btEditParcela = new javax.swing.JButton();
        lbPrecoTT2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfJuros = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        btGravarVendaPrazo = new javax.swing.JButton();
        btCancelar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel14.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel22.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel22.setText("Data da Venda:");

        try{
            javax.swing.text.MaskFormatter faixa= new javax.swing.text.MaskFormatter("##/##/####");
            tfDataCompra = new javax.swing.JFormattedTextField(faixa);
        }
        catch (Exception e){
        }
        tfDataCompra.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfDataCompraKeyTyped(evt);
            }
        });

        lbVendedorCod1.setText("0");
        lbVendedorCod1.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Vendedor", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        javax.swing.GroupLayout jPanel14Layout = new javax.swing.GroupLayout(jPanel14);
        jPanel14.setLayout(jPanel14Layout);
        jPanel14Layout.setHorizontalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbVendedorCod1, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel14Layout.setVerticalGroup(
            jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addComponent(lbVendedorCod1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel14Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel14Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel22)
                    .addComponent(tfDataCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Produtos", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tableJogo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Preço", "Quantidade"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableJogo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableJogoMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tableJogo);

        tfChaveJogo.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfChaveJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfChaveJogoActionPerformed(evt);
            }
        });
        tfChaveJogo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                tfChaveJogoKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfChaveJogoKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfChaveJogoKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tfChaveJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfChaveJogo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btAddJogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btAddJogo.setText("Adicionar Jogo");
        btAddJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btAddJogoActionPerformed(evt);
            }
        });

        btRemoveJogo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btRemoveJogo.setText("Remover Jogo");
        btRemoveJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btRemoveJogoActionPerformed(evt);
            }
        });

        btFechamento.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btFechamento.setText("Fechamento");
        btFechamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btFechamentoActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Carrinho de Compras", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        tableCarrinho.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Jogo", "Preço", "Quantidade", "Total"
            }
        ));
        tableCarrinho.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableCarrinhoMouseClicked(evt);
            }
        });
        jScrollPane7.setViewportView(tableCarrinho);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout jPanel12Layout = new javax.swing.GroupLayout(jPanel12);
        jPanel12.setLayout(jPanel12Layout);
        jPanel12Layout.setHorizontalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(btAddJogo)
                                .addGap(74, 74, 74)
                                .addComponent(btRemoveJogo))
                            .addGroup(jPanel12Layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(btFechamento)))
                        .addGap(0, 36, Short.MAX_VALUE))
                    .addGroup(jPanel12Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        jPanel12Layout.setVerticalGroup(
            jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel12Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel14, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel12Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btAddJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btRemoveJogo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btFechamento, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(22, Short.MAX_VALUE))
        );

        tpGuia.addTab("Venda", jPanel12);

        jpCompra.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel1.setText("Preço Pago:");

        tfPrecoPago.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfPrecoPagoKeyTyped(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel2.setText("Troco:");

        tfTroco.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfTrocoKeyTyped(evt);
            }
        });

        tfCliente.setText("1");
        tfCliente.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Código Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N
        tfCliente.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfClienteKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfClienteKeyTyped(evt);
            }
        });

        lbCliNome.setText("Cliente à vista");
        lbCliNome.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Nome", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        lbPrecoTT.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbPrecoTT.setText("0");
        lbPrecoTT.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Preço Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        javax.swing.GroupLayout jpCompraLayout = new javax.swing.GroupLayout(jpCompra);
        jpCompra.setLayout(jpCompraLayout);
        jpCompraLayout.setHorizontalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpCompraLayout.createSequentialGroup()
                        .addComponent(lbPrecoTT, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 86, Short.MAX_VALUE)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfPrecoPago, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addComponent(tfCliente, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(lbCliNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jpCompraLayout.setVerticalGroup(
            jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompraLayout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfCliente)
                    .addComponent(lbCliNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addGap(13, 13, 13)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(tfPrecoPago, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpCompraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(tfTroco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jpCompraLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lbPrecoTT, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel10.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btGravarVenda.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btGravarVenda.setText("Gravar Venda");
        btGravarVenda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarVendaActionPerformed(evt);
            }
        });

        btVendaPrazo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btVendaPrazo.setText("Venda a Prazo");
        btVendaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btVendaPrazoActionPerformed(evt);
            }
        });

        jButton1.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jButton1.setText("Cancelar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel10Layout = new javax.swing.GroupLayout(jPanel10);
        jPanel10.setLayout(jPanel10Layout);
        jPanel10Layout.setHorizontalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel10Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btGravarVenda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btVendaPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(252, 252, 252))
        );
        jPanel10Layout.setVerticalGroup(
            jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel10Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel10Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btGravarVenda, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btVendaPrazo)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jpCompra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jpCompra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(jPanel10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        tpGuia.addTab("Venda a Vista", jPanel3);

        jpCompra1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados da Venda", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btGeraParcela.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btGeraParcela.setText("Gerar Parcelas");
        btGeraParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGeraParcelaActionPerformed(evt);
            }
        });

        tableParcelas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Num.Parcela", "Data", "Preço"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Float.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tableParcelas.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        tableParcelas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableParcelasMouseClicked(evt);
            }
        });
        jScrollPane8.setViewportView(tableParcelas);

        btLimpar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btLimpar.setText("Limpar");
        btLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btLimparActionPerformed(evt);
            }
        });

        tfValorEntrada1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfValorEntrada1ActionPerformed(evt);
            }
        });
        tfValorEntrada1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfValorEntrada1KeyTyped(evt);
            }
        });

        jLabel20.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel20.setText("Valor de entrada:");

        jLabel23.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel23.setText("Número de parcelas:");

        tfNParcelas1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfNParcelas1KeyTyped(evt);
            }
        });

        btEditParcela.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btEditParcela.setText("Recalcular Parcelas");
        btEditParcela.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btEditParcelaActionPerformed(evt);
            }
        });

        lbPrecoTT2.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        lbPrecoTT2.setText("0");
        lbPrecoTT2.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Preço Total", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        jLabel4.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        jLabel4.setText("Juros:");

        tfJuros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                tfJurosKeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                tfJurosKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jpCompra1Layout = new javax.swing.GroupLayout(jpCompra1);
        jpCompra1.setLayout(jpCompra1Layout);
        jpCompra1Layout.setHorizontalGroup(
            jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompra1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jpCompra1Layout.createSequentialGroup()
                        .addComponent(btEditParcela)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btLimpar))
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(jpCompra1Layout.createSequentialGroup()
                        .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jpCompra1Layout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(tfValorEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jpCompra1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(tfJuros, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(9, 9, 9)
                        .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel23)
                            .addComponent(lbPrecoTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 10, Short.MAX_VALUE)
                        .addComponent(tfNParcelas1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jpCompra1Layout.createSequentialGroup()
                .addGap(130, 130, 130)
                .addComponent(btGeraParcela)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpCompra1Layout.setVerticalGroup(
            jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpCompra1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfValorEntrada1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(tfNParcelas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel23))
                .addGap(18, 18, 18)
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfJuros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbPrecoTT2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btGeraParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jpCompra1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btEditParcela, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel11.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Menu de opções", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 1, 12))); // NOI18N

        btGravarVendaPrazo.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btGravarVendaPrazo.setText("Gravar Venda");
        btGravarVendaPrazo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btGravarVendaPrazoActionPerformed(evt);
            }
        });

        btCancelar.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        btCancelar.setText("Cancelar");
        btCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btCancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel11Layout = new javax.swing.GroupLayout(jPanel11);
        jPanel11.setLayout(jPanel11Layout);
        jPanel11Layout.setHorizontalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(btGravarVendaPrazo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btCancelar)
                .addGap(349, 349, 349))
        );
        jPanel11Layout.setVerticalGroup(
            jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel11Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel11Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btGravarVendaPrazo, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jpCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, 231, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jpCompra1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27))
        );

        tpGuia.addTab("venda a Prazo", jPanel1);

        jLabel3.setFont(new java.awt.Font("Arial", 1, 20)); // NOI18N
        jLabel3.setText("Realizar Venda");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(tpGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 411, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(jLabel3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tpGuia, javax.swing.GroupLayout.PREFERRED_SIZE, 419, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadastroVenda() {
        VendaBEAN v = new VendaBEAN();
        ClienteBEAN c = contCli.localizarCodigo(Integer.valueOf(tfCliente.getText()));
        VendedorBEAN vend = cVend.localizar(Integer.valueOf(lbVendedorCod1.getText()));
        CaixaBEAN caixa = cCaixa.localizar(1);
        v.setCliente(c);
        v.setVendedor(vend);
        v.setCaixa(caixa);
        v.setVendaNparcelas(0);
        v.setVendaEntrada(Float.parseFloat(tfPrecoPago.getText()) - Float.parseFloat(tfTroco.getText()));
        v.setVendaValorTotal(Float.parseFloat(lbPrecoTT.getText()));

        try {
            String dataString = tfDataCompra.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
            v.setVendaData(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        contVenda.cadastrar(v);

        caixa.setCaixaDinheiro(caixa.getCaixaDinheiro() + v.getVendaEntrada());
        cCaixa.editar(caixa);

        for (JogoBEAN j : insertJogo) {
            for (JogoBEAN jogoEstoque : contJog.listarALL()) {
                if (jogoEstoque.getJoCodigo() == j.getJoCodigo()) {
                    JogoVendaBEAN jv = new JogoVendaBEAN();
                    JogoVendaPK jvpk = new JogoVendaPK();
                    jvpk.setJogo(j);
                    jvpk.setVenda(v);
                    jv.setChaveComposta(jvpk);
                    jv.setPrecoUnitarioReal(j.getJoPrecoPadrao());
                    jv.setQuantidade(j.getJoQtd());
                    cJV.cadastrar(jv);
                    int qtd = jogoEstoque.getJoQtd() - j.getJoQtd();
                    jogoEstoque.setJoQtd(qtd);
                    contJog.editar(jogoEstoque);
                }
            }
        }

    }

    private void limpaCampos1() {
        tfDataCompra.setText("");
        tfChaveJogo.setText("");
        povoaTabelaJogo(0);
        insertJogo.clear();
        preencheTabelaCarro();
        limpaCampos3();
        limpaCampos2();
    }

    private void limpaCampos2() {
        tfCliente.setText("1");
        lbCliNome.setText("Cliente à vista");
        lbPrecoTT.setText("0");
        tfTroco.setText("");
        tfPrecoPago.setText("");
        tpGuia.setSelectedIndex(0);
    }

    private void limpaCampos3() {
        tfValorEntrada1.setText("");
        tfNParcelas1.setText("");
        tfJuros.setText("");
        lbPrecoTT2.setText("0");

        insertData.clear();
        preecheTabelaPrazos();
        tpGuia.setSelectedIndex(1);
    }

    private void btGravarVendaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarVendaActionPerformed
        if (verificaCamposVenda() && verificaCamposVenda2()) {
            try {
                cadastroVenda();
                limpaCampos1();
                JOptionPane.showMessageDialog(null, "Venda Cadastrada com sucesso.");
                tpGuia.setSelectedIndex(0);
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Erro de Cadastrado verifique os dados.");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro!Preencha todos os campos.");
        }
    }//GEN-LAST:event_btGravarVendaActionPerformed
    private boolean verificaCamposVenda() {
        if (tfDataCompra.getText().equals("  /  /    ")
                || lbVendedorCod1.getText().equals("")
                || tableCarrinho.getRowCount() == 0) {
            return false;
        } else {
            return true;
        }
    }

    private boolean verificaCamposVenda2() {
        if (tfPrecoPago.getText().equals("")
                || tfTroco.getText().equals("")
                || lbPrecoTT.getText().equals("0")) {
            return false;
        } else {
            return true;
        }
    }

    private boolean verificaCamposVenda3() {
        if (lbPrecoTT2.getText().equals("0")
                || tfNParcelas1.getText().equals("")
                || tfValorEntrada1.getText().equals("")
                || tfJuros.getText().equals("")
                || tableParcelas.getRowCount() == 0) {
            return false;
        } else {
            return true;
        }
    }
    private void btFechamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btFechamentoActionPerformed
        if (verificaCamposVenda()) {
            float preco = 0;
            for (JogoBEAN j : insertJogo) {
                preco += (Float.parseFloat(j.getJoLote()));
            }
            lbPrecoTT.setText(String.valueOf(preco));
            tpGuia.setSelectedIndex(1);
        } else {
            JOptionPane.showMessageDialog(null, "Erro! Preencha todos os dados");
        }
    }//GEN-LAST:event_btFechamentoActionPerformed

    private void tableCarrinhoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableCarrinhoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableCarrinhoMouseClicked
    private void preencheTabelaCarro() {
        modelCarro = criaTabelaCarro();
        modelCarro.addColumn("Jogo");
        modelCarro.addColumn("Preço");
        modelCarro.addColumn("Quantidade");
        modelCarro.addColumn("Total");
        for (JogoBEAN j : insertJogo) {
            modelCarro.addRow(new Object[]{j.getJoNome(), j.getJoPrecoPadrao(), j.getJoQtd(), (j.getJoLote())});
        }
        tableCarrinho.setModel(modelCarro);
    }

    private DefaultTableModel criaTabelaCarro() {
        DefaultTableModel cTable = new DefaultTableModel() {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Float.class, java.lang.Integer.class, java.lang.Float.class};
            boolean[] canEdit = new boolean[]{
                false, false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;
        };
    return cTable;
    }
    private void btRemoveJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btRemoveJogoActionPerformed
        if (tableCarrinho.getSelectedRow() != -1) {
            int i = tableCarrinho.getSelectedRow();
            JogoBEAN a = insertJogo.get(i);
            for (JogoBEAN jogo : jogoList) {
                if (jogo.getJoCodigo() == a.getJoCodigo()) {
                    jogo.setJoQtd(jogo.getJoQtd() + a.getJoQtd());
                }
            }
            insertJogo.remove(i);
            preencheTabelaCarro();
            try {
                povoaTabelaJogo(Integer.parseInt(tfChaveJogo.getText()));
            } catch (Exception e) {

            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o jogo");
        }
    }//GEN-LAST:event_btRemoveJogoActionPerformed

    private void addQtd(JogoBEAN j, float preco) {
        int qtd = 0;
        try {
            qtd = Integer.parseInt(JOptionPane.showInputDialog("Digite a Quantidade de jogos"));
        } catch (Exception e) {

        }
        if (qtd <= j.getJoQtd() && qtd > 0) {

            JogoBEAN wtf = new JogoBEAN();
            wtf.setJoCodigo(j.getJoCodigo());
            wtf.setJoNome(j.getJoNome());
            wtf.setJoQtd(qtd);
            wtf.setJoPrecoPadrao(preco);
            wtf.setJoLote(String.valueOf(preco * qtd));
            insertJogo.add(wtf);
            preencheTabelaCarro();
            for (JogoBEAN jogo : jogoList) {
                if (jogo.getJoCodigo() == wtf.getJoCodigo()) {
                    jogo.setJoQtd(jogo.getJoQtd() - wtf.getJoQtd());
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Quantidade inválida");
        }

        try {
            povoaTabelaJogo(Integer.parseInt(tfChaveJogo.getText()));
        } catch (Exception e) {
        }
    }
    private void btAddJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btAddJogoActionPerformed
        if (tableJogo.getSelectedRow() != -1) {
            JogoBEAN j = new JogoBEAN();

            for (JogoBEAN jogo : jogoList) {
                if (jogo.getJoCodigo() == Integer.parseInt(tfChaveJogo.getText())) {
                    j = jogo;
                }
            }

            float lucro = ((j.getLucro().getLucPorcentagem() * j.getJoPrecoPadrao()) / 100);
            float precoSug = lucro + j.getJoPrecoPadrao();
            float preco = 0;

            try {
                preco = Float.parseFloat(JOptionPane.showInputDialog("Digite o preço praticado do Jogo"
                        + "\n" + "Preço sugerido: " + precoSug));
            } catch (Exception e) {

            }

            if (preco > 0) {
                if (preco >= precoSug) {
                    addQtd(j, preco);
                } else {
                    int dialogButton = JOptionPane.YES_NO_OPTION;
                    int dialogResult = JOptionPane.showConfirmDialog(this, "Preço abaixo do padrão. Tem certeza que deseja prosseguir", "Alerta", dialogButton);
                    if (dialogResult == 0) {
                        addQtd(j, preco);
                    } else {
                        JOptionPane.showMessageDialog(null, "Cancelado");
                    }
                }
            } else {
                JOptionPane.showMessageDialog(null, "Preço inválido");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Selecione o jogo");
        }
    }//GEN-LAST:event_btAddJogoActionPerformed

    private void tfChaveJogoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogoKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfChaveJogoKeyTyped

    private void tfChaveJogoKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogoKeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChaveJogoKeyPressed

    private void tfChaveJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfChaveJogoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfChaveJogoActionPerformed

    private void tableJogoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableJogoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableJogoMouseClicked

    private void btGeraParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGeraParcelaActionPerformed
        try {
            insertData.clear();
            int t = Integer.parseInt(tfNParcelas1.getText());
            float precoTT = Float.parseFloat((lbPrecoTT2.getText()));
            float precoParcelaTT = precoTT - Float.parseFloat((tfValorEntrada1.getText()));
            for (int c = 1; c <= t; c++) {
                java.sql.Date data = null;
                try {
                    String dataString = tfDataCompra.getText();
                    DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
                    data = new java.sql.Date(fmt.parse(dataString).getTime());
                } catch (ParseException e) {
                    e.printStackTrace();
                }
                VendaAPrazoBEAN nota = new VendaAPrazoBEAN();
                int m = data.getMonth();
                data.setMonth(m + c);
                float valor = precoParcelaTT / t;
                nota.setVapValorParcela(valor);
                nota.setVapNumParcela(c);
                nota.setVapData(data);
                insertData.add(nota);
            }
            preecheTabelaPrazos();
        } catch (Exception e) {
         JOptionPane.showMessageDialog(null, "Erro, verifique os campos");
        }
    }//GEN-LAST:event_btGeraParcelaActionPerformed

    private void tableParcelasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableParcelasMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tableParcelasMouseClicked
    private void preecheTabelaPrazos() {
        modelPrazo = criaTabelaPrazos();
        modelPrazo.addColumn("Num.Parcela");
        modelPrazo.addColumn("Data");
        modelPrazo.addColumn("Preço-Parcela");
        for (VendaAPrazoBEAN n : insertData) {
            modelPrazo.addRow(new Object[]{n.getVapNumParcela(), n.getVapData(), n.getVapValorParcela()});
        }
        tableParcelas.setModel(modelPrazo);
    }

    private DefaultTableModel criaTabelaPrazos() {
        DefaultTableModel dTable2 = new DefaultTableModel() {
            Class[] types = new Class[]{
                java.lang.Integer.class,
                java.lang.String.class,
                java.lang.Float.class,};
            boolean[] canEdit = new boolean[]{
                false, false, false};

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;
        };
    return dTable2;
    }
    private void btLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btLimparActionPerformed
        insertData.clear();
        preecheTabelaPrazos();
    }//GEN-LAST:event_btLimparActionPerformed

    private void tfValorEntrada1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfValorEntrada1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfValorEntrada1ActionPerformed
    private void cadVendaAPrazo() {
        VendaBEAN v = new VendaBEAN();
        ClienteBEAN c = contCli.localizarCodigo(Integer.valueOf(tfCliente.getText()));
        VendedorBEAN vend = cVend.localizar(Integer.valueOf(lbVendedorCod1.getText()));
        CaixaBEAN caixa = cCaixa.localizar(1);
        v.setCliente(c);
        v.setVendedor(vend);
        v.setCaixa(caixa);
        v.setVendaNparcelas(Integer.parseInt(tfNParcelas1.getText()));
        v.setVendaEntrada(Float.parseFloat(tfValorEntrada1.getText()));
        v.setVendaValorTotal(Float.parseFloat(lbPrecoTT2.getText()));
        try {
            String dataString = tfDataCompra.getText();
            DateFormat fmt = new SimpleDateFormat("dd/MM/yyyy");
            java.sql.Date data = new java.sql.Date(fmt.parse(dataString).getTime());
            v.setVendaData(data);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        contVenda.cadastrar(v);

        caixa.setCaixaDinheiro(caixa.getCaixaDinheiro() + v.getVendaEntrada());
        cCaixa.editar(caixa);

        for (VendaAPrazoBEAN ndca : insertData) {
            VendaAPrazoBEAN nota = new VendaAPrazoBEAN();
            nota.setVapData(ndca.getVapData());
            nota.setVapValorParcela(ndca.getVapValorParcela());
            nota.setVapNumParcela(ndca.getVapNumParcela());
            nota.setVapSituacao("Pendente");
            nota.setVenda(v);
            contVendaPrazo.cadastrar(nota);
        }

        for (JogoBEAN j : insertJogo) {
            for (JogoBEAN jogoEstoque : contJog.listarALL()) {
                if (jogoEstoque.getJoCodigo() == j.getJoCodigo()) {
                    JogoVendaBEAN jv = new JogoVendaBEAN();
                    JogoVendaPK jvpk = new JogoVendaPK();
                    jvpk.setJogo(j);
                    jvpk.setVenda(v);
                    jv.setChaveComposta(jvpk);
                    jv.setPrecoUnitarioReal(j.getJoPrecoPadrao());
                    jv.setQuantidade(j.getJoQtd());
                    cJV.cadastrar(jv);
                    jogoEstoque.setJoQtd(jogoEstoque.getJoQtd() - j.getJoQtd());
                    contJog.editar(jogoEstoque);
                }
            }
        }

    }

    private void btGravarVendaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btGravarVendaPrazoActionPerformed
        if (verificaCamposVenda() && verificaCamposVenda3()) {
            if (lbCliNome.getText().equals("Cliente à vista")) {
                JOptionPane.showMessageDialog(null, "Selecione um cliente");
            } else {
                cadVendaAPrazo();
                limpaCampos1();
                JOptionPane.showMessageDialog(null, "Cadastrado com sucesso");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Erro!Preencha todos os campos.");
        }
    }//GEN-LAST:event_btGravarVendaPrazoActionPerformed

    private void tfClienteKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfClienteKeyTyped

    private void tfClienteKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfClienteKeyReleased
        try {
            ClienteBEAN c = contCli.localizarCodigo(Integer.parseInt(tfCliente.getText()));
            lbCliNome.setText(c.getCliNome());
        } catch (Exception e) {
            lbCliNome.setText("Cliente não encontrado");
        }
    }//GEN-LAST:event_tfClienteKeyReleased
    private void povoaTabelaJogo(int c) {
        modelJogo = criaTabelaJogo();
        modelJogo.addColumn("Jogo");
        modelJogo.addColumn("Preço");
        modelJogo.addColumn("Quantidade");
        for (JogoBEAN j : jogoList) {
            if ((j.getJoCodigo() == c) && (j.getJoTipo().equals("Venda"))) {
                modelJogo.addRow(new Object[]{j.getJoNome(), j.getJoPrecoPadrao(), j.getJoQtd()});
            }
        }
        tableJogo.setModel(modelJogo);
    }

    private DefaultTableModel criaTabelaJogo() {
        DefaultTableModel cTable = new DefaultTableModel() {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.Integer.class};
            boolean[] canEdit = new boolean[]{
                false, false, false
            };

            @Override
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit[columnIndex];
            }
        ;
        };
    return cTable;
    }
    private void tfChaveJogoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfChaveJogoKeyReleased
        int c;
        if (tfChaveJogo.getText().equals("")) {
            c = 0;
        } else {
            c = Integer.parseInt(tfChaveJogo.getText());
        }
        povoaTabelaJogo(c);
    }//GEN-LAST:event_tfChaveJogoKeyReleased

    private void tfJurosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJurosKeyTyped
        if (!pct.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfJurosKeyTyped

    private void tfValorEntrada1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfValorEntrada1KeyTyped
        if (!pct.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfValorEntrada1KeyTyped

    private void tfNParcelas1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfNParcelas1KeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfNParcelas1KeyTyped

    private void tfPrecoPagoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfPrecoPagoKeyTyped
        if (!pct.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfPrecoPagoKeyTyped

    private void tfTrocoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfTrocoKeyTyped
        if (!pct.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfTrocoKeyTyped

    private void tfDataCompraKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfDataCompraKeyTyped
        if (!numeros.contains(evt.getKeyChar() + "")) {
            evt.consume();
        }
    }//GEN-LAST:event_tfDataCompraKeyTyped

    private void btVendaPrazoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btVendaPrazoActionPerformed
        if (verificaCamposVenda()) {
            if (lbCliNome.getText().equals("Cliente à vista") || lbCliNome.getText().equals("Cliente não encontrado")) {
                JOptionPane.showMessageDialog(null, "Selecione um cliente");
            } else {
                tpGuia.setSelectedIndex(2);
                lbPrecoTT2.setText(lbPrecoTT.getText());
            }
        } else {
            JOptionPane.showMessageDialog(null, "Preencha os campos");
        }
    }//GEN-LAST:event_btVendaPrazoActionPerformed

    private void tfJurosKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_tfJurosKeyReleased
        try {
            float juro = (Float.parseFloat(tfJuros.getText()) / 100) * (Float.parseFloat(lbPrecoTT.getText()));
            float preco = Float.parseFloat(lbPrecoTT.getText()) + juro;
            lbPrecoTT2.setText(String.valueOf(preco));
        } catch (Exception e) {
            lbPrecoTT2.setText(lbPrecoTT.getText());
        }
    }//GEN-LAST:event_tfJurosKeyReleased

    private void btEditParcelaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btEditParcelaActionPerformed
        if (tableParcelas.getSelectedRow() != -1) {

        } else {
            JOptionPane.showMessageDialog(null, "Selecione a parcela");
        }
        Editar parcelas
    }//GEN-LAST:event_btEditParcelaActionPerformed

    private void btCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btCancelarActionPerformed
        limpaCampos3();
    }//GEN-LAST:event_btCancelarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpaCampos2();
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMVendaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMVendaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMVendaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMVendaNova.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMVendaNova().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btAddJogo;
    private javax.swing.JButton btCancelar;
    private javax.swing.JButton btEditParcela;
    private javax.swing.JButton btFechamento;
    private javax.swing.JButton btGeraParcela;
    private javax.swing.JButton btGravarVenda;
    private javax.swing.JButton btGravarVendaPrazo;
    private javax.swing.JButton btLimpar;
    private javax.swing.JButton btRemoveJogo;
    private javax.swing.JButton btVendaPrazo;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel14;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JPanel jpCompra;
    private javax.swing.JPanel jpCompra1;
    private javax.swing.JLabel lbCliNome;
    private javax.swing.JLabel lbPrecoTT;
    private javax.swing.JLabel lbPrecoTT2;
    private javax.swing.JLabel lbVendedorCod1;
    private javax.swing.JTable tableCarrinho;
    private javax.swing.JTable tableJogo;
    private javax.swing.JTable tableParcelas;
    private javax.swing.JTextField tfChaveJogo;
    private javax.swing.JTextField tfCliente;
    private javax.swing.JFormattedTextField tfDataCompra;
    private javax.swing.JTextField tfJuros;
    private javax.swing.JTextField tfNParcelas1;
    private javax.swing.JTextField tfPrecoPago;
    private javax.swing.JTextField tfTroco;
    private javax.swing.JTextField tfValorEntrada1;
    private javax.swing.JTabbedPane tpGuia;
    // End of variables declaration//GEN-END:variables
}
